//! Produce the `derived_refseqgene_placements.json` artifact (#728): for each
//! pinned `NG_` version in an input list, fetch its GenBank record + sequence
//! from NCBI, derive its chromosomal placement from the record's exon
//! annotation + cdot, validate by full-sequence comparison against the genome,
//! and write the validated placements.
//!
//! This is the prepare-time **producer** for the runtime-consumption path
//! (`conformance`/`reference::derived_placement` + the manifest's
//! `derived_refseqgene_placements` field). It runs locally (it needs a prepared
//! reference for cdot + genome, and network for EFetch); the committed/manifest
//! artifact it writes is then consumed offline. Decline-rather-than-mis-anchor
//! is enforced by `derive_ng_placement` — an accession that cannot be proven
//! is simply omitted (reported), never guessed.
//!
//! Run:
//!   cargo run --features dev --example derive_ng_placements -- \
//!     --manifest <ref>/manifest.json --accessions ng_versions.txt \
//!     --out <ref>/derived_refseqgene_placements.json [--builds GRCh38,GRCh37]

use std::path::PathBuf;
use std::process::ExitCode;

use clap::Parser;

use ferro_hgvs::reference::multi_fasta::MultiFastaProvider;

#[derive(Parser, Debug)]
#[command(about = "Derive version-independent NG_/LRG_ genomic placements (#728)")]
struct Cli {
    /// Prepared-reference manifest (for cdot + genome).
    #[arg(long)]
    manifest: PathBuf,
    /// Newline-delimited file of exact `NG_` versions to derive (e.g.
    /// `NG_012337.1`). Blank lines and `#` comments are ignored.
    #[arg(long)]
    accessions: PathBuf,
    /// Output JSON path (`derived_refseqgene_placements.json`).
    #[arg(long)]
    out: PathBuf,
    /// Comma-separated genome builds to derive for (default `GRCh38`).
    #[arg(long, default_value = "GRCh38")]
    builds: String,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: &Cli) -> anyhow::Result<()> {
    use ferro_hgvs::reference::ng_placement_builder::derive_placements_for_accessions;

    let provider = MultiFastaProvider::from_manifest(&cli.manifest)
        .map_err(|e| anyhow::anyhow!("load manifest {}: {e}", cli.manifest.display()))?;
    let accessions = read_accession_list(&cli.accessions)?;
    let builds: Vec<String> = cli
        .builds
        .split(',')
        .map(|s| s.trim().to_string())
        .collect();

    let description = format!(
        "GENERATED by `cargo run --features dev --example derive_ng_placements`. \
         Version-independent NG_/LRG_ placements (#728) derived from each NG_'s \
         GenBank exon annotation + cdot, validated by full-sequence comparison. \
         Source manifest: {}.",
        cli.manifest.display()
    );
    let (artifact, declined) =
        derive_placements_for_accessions(&provider, &accessions, &builds, description)
            .map_err(|e| anyhow::anyhow!("derive: {e}"))?;

    let json = artifact
        .to_json()
        .map_err(|e| anyhow::anyhow!("serialize: {e}"))?;
    std::fs::write(&cli.out, &json)
        .map_err(|e| anyhow::anyhow!("write {}: {e}", cli.out.display()))?;
    println!(
        "Derived {} placement(s), {} declined. Wrote {}.",
        artifact.placements.len(),
        declined,
        cli.out.display()
    );
    Ok(())
}

/// Read exact accessions from a newline-delimited file (skipping blanks/`#`).
fn read_accession_list(path: &std::path::Path) -> anyhow::Result<Vec<String>> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;
    Ok(text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect())
}
