//! Extract the hermetic reference fixture that unlocks the **projection**
//! dimensions of the HGVS spec test enumeration.
//!
//! `generate_spec_enumeration` enumerates every spec-derived HGVS string across
//! five projection axes (`g`/`c`/`n`/`r`/`p`). Projection needs real reference
//! data — transcript bases + CDS, exon structure, chromosome bases, and
//! `NG_`/`LRG_` → chromosome placements — which lives only in a multi-GB
//! prepared reference CI does not have. This generator runs the *exact* pass
//! the enumeration will replay ([`ferro_hgvs::conformance::spec_projection::project_all_axes`]) against
//! a real manifest through a [`RecordingProvider`], and commits precisely the
//! slice it touched as a
//! [`WindowFixture`](ferro_hgvs::conformance::reference_window::WindowFixture).
//!
//! Mirrors `extract_mutalyzer_genomic_windows.rs` — same recorder, same padded
//! window merging, same "committed and reviewed, never regenerated in CI"
//! contract. `--check` is a *local* guard: run against the same manifest, it
//! fails if the committed fixture no longer matches a fresh extraction.
//!
//! Run:   `cargo run --features dev --example extract_spec_enumeration_windows -- --manifest PATH`
//! Check: `cargo run --features dev --example extract_spec_enumeration_windows -- --check`

use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::sync::Arc;

use clap::Parser;
use ferro_hgvs::conformance::spec_projection;
use ferro_hgvs::data::projection::Projector;
use ferro_hgvs::project::VariantProjector;
use ferro_hgvs::{parse_hgvs, MultiFastaProvider};

#[path = "common/recording.rs"]
mod recording;
#[path = "common/spec_harvest.rs"]
mod spec_harvest;

use recording::{build_window_fixture, RecordingProvider};
use spec_harvest::{prefix, sources};

/// Committed fixture metadata path (repo-relative — never a machine-local
/// path). The bases live in two sidecar FASTAs beside it; see
/// [`spec_projection::render_slice`].
const WINDOWS_JSON: &str = "tests/fixtures/grammar/spec_enumeration_windows.json";
const FIXTURE_DIR: &str = "tests/fixtures/grammar";

#[derive(Parser, Debug)]
#[command(about = "Extract hermetic reference windows for the spec-enumeration projection axes")]
struct Cli {
    /// Path to the vendored spec checkout.
    #[arg(long, default_value = "assets/hgvs-nomenclature")]
    spec_dir: PathBuf,
    /// Prepared-reference manifest. Falls back to `$FERRO_MANIFEST`.
    #[arg(long)]
    manifest: Option<PathBuf>,
    /// Compare the committed fixture to a fresh extraction; exit non-zero on
    /// drift and write nothing. Requires the manifest.
    #[arg(long)]
    check: bool,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: &Cli) -> anyhow::Result<ExitCode> {
    let Some(manifest) = cli
        .manifest
        .clone()
        .or_else(|| std::env::var("FERRO_MANIFEST").ok().map(PathBuf::from))
    else {
        eprintln!("no manifest (pass --manifest or set FERRO_MANIFEST); cannot extract windows");
        return Ok(ExitCode::FAILURE);
    };

    let provider = Arc::new(
        MultiFastaProvider::from_manifest(&manifest)
            .map_err(|e| anyhow::anyhow!("load manifest {}: {e}", manifest.display()))?,
    );
    let cdot = provider
        .cdot_mapper()
        .ok_or_else(|| anyhow::anyhow!("manifest has no cdot; cannot project"))?
        .clone();

    let recorder = RecordingProvider::new(Arc::clone(&provider));
    let projector = VariantProjector::new(Projector::new(cdot), recorder.clone());

    let targets = spec_targets(&cli.spec_dir)?;
    eprintln!("projecting {} spec targets...", targets.len());
    let mut projected = 0usize;
    for (i, target) in targets.iter().enumerate() {
        if i % 50 == 0 {
            eprintln!("  [{i}/{}] {target}", targets.len());
        }
        // Errors and panics still leave their reference accesses recorded, which
        // is all this pass is for.
        let _ = catch_unwind(AssertUnwindSafe(|| {
            let Ok(variant) = parse_hgvs(target) else {
                return;
            };
            projected += 1;
            let _ = spec_projection::project_all_axes(&projector, &variant);
        }));
    }

    // Record only the manifest's file name: an absolute path would leak the
    // local layout into the repo and churn `--check` per machine.
    let captured_from = manifest
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "manifest.json".to_string());
    let description = format!(
        "GENERATED by `cargo run --features dev --example extract_spec_enumeration_windows`. \
         Hermetic reference slice for the spec-enumeration projection axes: every transcript, \
         padded genomic window, and NG_/LRG_ placement the five-axis projection pass over the \
         HGVS spec corpus touches. Do not hand-edit; regenerate from a prepared-reference \
         manifest. Margin: {} bp.",
        recording::PAD
    );

    // Keep transcript records only. `NM_`/`NR_` and an LRG *transcript*
    // (`LRG_199t1`) are mRNA-sized; an `NG_` or a bare `LRG_199` is the
    // multi-hundred-KB genomic record, which would bloat the committed file and
    // is served through its captured placement instead.
    let fixture = build_window_fixture(&recorder, captured_from, description, |tx| {
        tx.id.starts_with("NM_") || tx.id.starts_with("NR_") || is_lrg_transcript(&tx.id)
    });
    let (json, tx_fasta, win_fasta) = spec_projection::render_slice(&fixture)
        .map_err(|e| anyhow::anyhow!("serialize fixture: {e}"))?;
    let dir = Path::new(FIXTURE_DIR);
    let files = [
        (PathBuf::from(WINDOWS_JSON), json),
        (dir.join(spec_projection::SLICE_TRANSCRIPTS_FASTA), tx_fasta),
        (dir.join(spec_projection::SLICE_WINDOWS_FASTA), win_fasta),
    ];

    if cli.check {
        for (path, rendered) in &files {
            let committed = std::fs::read_to_string(path).unwrap_or_default();
            if committed != *rendered {
                eprintln!(
                    "{} is OUT OF DATE — regenerate with `cargo run --features dev \
                     --example extract_spec_enumeration_windows -- --manifest <manifest>`.",
                    path.display()
                );
                return Ok(ExitCode::FAILURE);
            }
        }
        println!("committed reference slice is up to date ({projected} projected inputs).");
        return Ok(ExitCode::SUCCESS);
    }

    for (path, rendered) in &files {
        std::fs::write(path, rendered)
            .map_err(|e| anyhow::anyhow!("write {}: {e}", path.display()))?;
    }
    println!(
        "Wrote {WINDOWS_JSON}: {} transcripts, {} windows, {} placements \
         (from {projected} projected inputs of {} spec targets).",
        fixture.transcripts.len(),
        fixture.genomic.len(),
        fixture.placements.len(),
        targets.len()
    );
    Ok(ExitCode::SUCCESS)
}

/// Is `id` an LRG **transcript** record (`LRG_199t1`) rather than the LRG
/// genomic record (`LRG_199`)? Only the former is mRNA-sized.
fn is_lrg_transcript(id: &str) -> bool {
    let Some(rest) = id.strip_prefix("LRG_") else {
        return false;
    };
    match rest.split_once('t') {
        Some((num, tx)) => {
            !num.is_empty()
                && num.bytes().all(|b| b.is_ascii_digit())
                && !tx.is_empty()
                && tx.bytes().all(|b| b.is_ascii_digit())
        }
        None => false,
    }
}

/// Every distinct spec-derived string ferro is run against, in the same
/// default-prefixed form the enumeration uses (`target_for`). Sorted and
/// deduplicated so the recording — and therefore the committed fixture — is
/// deterministic.
fn spec_targets(spec_dir: &Path) -> anyhow::Result<Vec<String>> {
    let candidates = sources::discover(spec_dir)?;
    let mut targets: Vec<String> = candidates
        .iter()
        .map(|c| prefix::default_prefixed(&c.input).unwrap_or_else(|| c.input.clone()))
        .collect();
    targets.sort();
    targets.dedup();
    Ok(targets)
}
