//! Extract the hermetic reference slice behind the harvested-case gate.
//!
//! Every row in `tests/fixtures/case-harvest/cases.json` is sequence-dependent:
//! the inversion rows compare a block against its own reverse complement, the
//! repeat rows read the tract, the 3'rule rows read the bases they would shift
//! over, and the genomic stability rows read spans of up to 1,193 bp. None of
//! that can run under `MockProvider`, and running it under the prepared
//! reference would make the whole suite a manifest-or-skip test that CI silently
//! skips. So the usual pattern applies: run the real pass against a real
//! manifest through a [`RecordingProvider`], and commit precisely the slice it
//! touched.
//!
//! # `serve_transcripts_whole` is load-bearing, not a size tweak
//!
//! A window captured from a pass is exactly as wide as that pass happened to
//! read, which makes the fixture self-fulfilling: it serves the recorded pass
//! and fails any pass that reads further. Normalization turns such a failure
//! into `Ok(input-unchanged)`, which for a lone-member row is byte-identical to
//! a correct answer — so the gate goes green with the defect fully present.
//! Widening every transcript's window to the whole stored sequence removes the
//! failure mode by construction: there is no "outside the window" left for a
//! transcript. `tests/it/case_harvest.rs` asserts the widening hermetically, so
//! a regenerated fixture that lost it fails rather than going quietly blind, and
//! the same file's [`AuditedProvider`] assertion catches the genomic half.
//!
//! [`AuditedProvider`]: ferro_hgvs::conformance::audited_provider::AuditedProvider
//!
//! Run:   `cargo run --features dev --example extract_case_harvest_windows -- --manifest PATH`
//! Check: `cargo run --features dev --example extract_case_harvest_windows -- --check --manifest PATH`

use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::sync::Arc;

use clap::Parser;
use ferro_hgvs::conformance::case_harvest::{Fixture, CASES_PATH, WINDOWS_PATH};
use ferro_hgvs::conformance::reference_window::{GenomicWindow, WindowFixture};
use ferro_hgvs::error_handling::ErrorConfig;
use ferro_hgvs::hgvs::parser::parse_hgvs_with_config;
use ferro_hgvs::{MultiFastaProvider, NormalizeConfig, Normalizer, ShuffleDirection};

#[path = "common/recording.rs"]
mod recording;

use recording::{build_window_fixture, RecordingProvider};

#[derive(Parser, Debug)]
#[command(about = "Extract the hermetic reference slice for the harvested-case gate")]
struct Cli {
    /// Prepared-reference manifest. Falls back to `$FERRO_MANIFEST`.
    #[arg(long)]
    manifest: Option<PathBuf>,
    /// Compare the committed slice to a fresh extraction; exit non-zero on
    /// drift and write nothing. Requires the manifest.
    #[arg(long)]
    check: bool,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    // Refuse a `FERRO_PARTITION` naming no arm before any work, so a
    // misspelling cannot be served by the shipped rule under a candidate's
    // name. See `tests/it/partition_switch_wiring.rs`.
    if let Some(message) = ferro_hgvs::normalize::partition_switch_startup_error() {
        eprintln!("error: {message}");
        return ExitCode::FAILURE;
    }
    match run(&cli) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: &Cli) -> anyhow::Result<ExitCode> {
    let Some(manifest) = cli
        .manifest
        .clone()
        .or_else(|| std::env::var("FERRO_MANIFEST").ok().map(PathBuf::from))
    else {
        eprintln!("no manifest (pass --manifest or set FERRO_MANIFEST); cannot extract windows");
        return Ok(ExitCode::FAILURE);
    };

    let cases = Fixture::from_json_path(Path::new(CASES_PATH))
        .map_err(|e| anyhow::anyhow!("load {CASES_PATH}: {e}"))?;

    let provider = Arc::new(
        MultiFastaProvider::from_manifest(&manifest)
            .map_err(|e| anyhow::anyhow!("load manifest {}: {e}", manifest.display()))?,
    );
    let recorder = RecordingProvider::new(Arc::clone(&provider));

    for case in &cases.cases {
        // Capture the row's own reads, then the reads of re-normalizing its
        // answer — the gate asserts every answer is a fixed point, so the second
        // pass is part of what the slice must serve.
        let first = normalize(&recorder, &case.input)?;
        if let Some(output) = first {
            normalize(&recorder, &output)?;
        }
    }

    // Record only the manifest's file name: an absolute path would leak the
    // local layout into the repo and churn `--check` per machine.
    let captured_from = manifest
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "manifest.json".to_string());
    let description = format!(
        "GENERATED by `cargo run --features dev --example extract_case_harvest_windows`. \
         Hermetic reference slice for the harvested-case gate: every transcript (served WHOLE) \
         and padded genomic window the normalize pass over cases.json touches. Do not hand-edit; \
         regenerate from a prepared-reference manifest. Margin: {} bp.",
        recording::PAD
    );

    // mRNA-sized records only. An `NG_`/`LRG_` genomic record resolved as a
    // "transcript" carries hundreds of KB of sequence — and the pre-commit hook
    // rejects an added file over 500 KB — so those are served through their
    // captured windows and placements instead.
    let mut fixture = build_window_fixture(&recorder, captured_from, description, |tx| {
        tx.id.starts_with("NM_") || tx.id.starts_with("NR_") || is_lrg_transcript(&tx.id)
    });
    serve_transcripts_whole(&mut fixture);

    let rendered = fixture
        .to_json()
        .map_err(|e| anyhow::anyhow!("serialize fixture: {e}"))?;

    if cli.check {
        let committed = std::fs::read_to_string(WINDOWS_PATH).unwrap_or_default();
        if committed != rendered {
            eprintln!(
                "{WINDOWS_PATH} is OUT OF DATE — regenerate with `cargo run --features dev \
                 --example extract_case_harvest_windows -- --manifest <manifest>`."
            );
            return Ok(ExitCode::FAILURE);
        }
        println!(
            "committed reference slice is up to date ({} rows, {} transcripts, {} windows).",
            cases.cases.len(),
            fixture.transcripts.len(),
            fixture.genomic.len()
        );
        return Ok(ExitCode::SUCCESS);
    }

    std::fs::write(WINDOWS_PATH, rendered)
        .map_err(|e| anyhow::anyhow!("write {WINDOWS_PATH}: {e}"))?;
    println!(
        "Wrote {WINDOWS_PATH}: {} transcripts, {} windows, {} placements (from {} rows).",
        fixture.transcripts.len(),
        fixture.genomic.len(),
        fixture.placements.len(),
        cases.cases.len()
    );
    Ok(ExitCode::SUCCESS)
}

/// Normalize `input` through the shipped lenient path — the same entry point
/// `tests/it/case_harvest.rs` replays — and return its rendered answer.
///
/// A row that fails to normalize still recorded whatever it read, which is all
/// this pass is for; the gate is where a failure is a failure. A row that fails
/// to *parse* is a corpus typo and aborts, because the slice would then silently
/// omit that row's bases.
fn normalize(recorder: &RecordingProvider, input: &str) -> anyhow::Result<Option<String>> {
    let config = ErrorConfig::lenient();
    let parsed = parse_hgvs_with_config(input, config.clone())
        .map_err(|e| anyhow::anyhow!("case {input:?} does not parse: {e}"))?;
    let normalize_config = NormalizeConfig::for_entry_point(ShuffleDirection::ThreePrime, config);
    match Normalizer::with_config(recorder.clone(), normalize_config).normalize(&parsed.result) {
        Ok(v) => Ok(Some(v.to_string())),
        Err(e) => {
            eprintln!("  note: {input} did not normalize ({e})");
            Ok(None)
        }
    }
}

/// Widen every window whose accession is also a stored transcript so it covers
/// that transcript whole.
///
/// This is a fidelity fix. The normalizer reaches a transcript through
/// `get_genomic_sequence` as well as `get_transcript`, so the recorder files
/// those reads under `contig_ranges` and the accession lands in the fixture's
/// `genomic` map. That makes `WindowProvider::is_known_contig` true for it,
/// which routes **`get_sequence` for the transcript** through the
/// genomic-window path instead of the whole stored sequence — so every read
/// outside the captured window errors, even though the bases are sitting right
/// there in `transcripts`.
///
/// Serving the accession whole removes the failure mode by construction.
fn serve_transcripts_whole(fixture: &mut WindowFixture) {
    for transcript in &fixture.transcripts {
        let Some(bases) = transcript.sequence.clone() else {
            continue;
        };
        fixture
            .genomic
            .retain(|window| window.contig != transcript.id);
        fixture.genomic.push(GenomicWindow {
            contig: transcript.id.clone(),
            start: 0,
            bases,
        });
        fixture
            .contig_lengths
            .insert(transcript.id.clone(), transcript.sequence_length());
    }
    // Deterministic order for a stable `--check`.
    fixture
        .genomic
        .sort_by(|a, b| (a.contig.as_str(), a.start).cmp(&(b.contig.as_str(), b.start)));
}

/// Is `id` an LRG **transcript** record (`LRG_199t1`) rather than the LRG
/// genomic record (`LRG_199`)? Only the former is mRNA-sized.
fn is_lrg_transcript(id: &str) -> bool {
    let Some(rest) = id.strip_prefix("LRG_") else {
        return false;
    };
    match rest.split_once('t') {
        Some((num, tx)) => {
            !num.is_empty()
                && num.bytes().all(|b| b.is_ascii_digit())
                && !tx.is_empty()
                && tx.bytes().all(|b| b.is_ascii_digit())
        }
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::{is_lrg_transcript, serve_transcripts_whole};
    use ferro_hgvs::conformance::reference_window::{GenomicWindow, WindowFixture};
    use ferro_hgvs::reference::transcript::{Exon, GenomeBuild, ManeStatus, Strand, Transcript};

    fn transcript(id: &str, bases: &str) -> Transcript {
        Transcript::new(
            id.to_string(),
            Some("TEST".to_string()),
            Strand::Plus,
            bases.to_string(),
            Some(1),
            Some(bases.len() as u64),
            vec![Exon::new(1, 1, bases.len() as u64)],
            None,
            None,
            None,
            GenomeBuild::default(),
            ManeStatus::default(),
            None,
            None,
        )
    }

    #[test]
    fn an_lrg_transcript_is_kept_and_an_lrg_genomic_record_is_not() {
        assert!(is_lrg_transcript("LRG_199t1"));
        assert!(!is_lrg_transcript("LRG_199"));
        assert!(!is_lrg_transcript("NG_008660.1"));
        assert!(!is_lrg_transcript("LRG_t1"));
    }

    #[test]
    fn a_narrow_transcript_window_is_replaced_by_the_whole_sequence() {
        // The measured defect: the recorder captured a 4 bp window on the
        // transcript's own accession, which is what `WindowProvider` would then
        // serve `get_sequence` from — erroring on every read outside it.
        let mut fixture = WindowFixture {
            transcripts: vec![transcript("NM_TEST.1", "ACGTACGTACGT")],
            genomic: vec![GenomicWindow {
                contig: "NM_TEST.1".to_string(),
                start: 4,
                bases: "ACGT".to_string(),
            }],
            ..Default::default()
        };
        serve_transcripts_whole(&mut fixture);
        assert_eq!(fixture.genomic.len(), 1);
        assert_eq!(fixture.genomic[0].start, 0);
        assert_eq!(fixture.genomic[0].bases, "ACGTACGTACGT");
        assert_eq!(fixture.contig_lengths.get("NM_TEST.1"), Some(&12));
    }

    #[test]
    fn a_genomic_window_on_another_accession_is_left_alone() {
        let mut fixture = WindowFixture {
            transcripts: vec![transcript("NM_TEST.1", "ACGT")],
            genomic: vec![GenomicWindow {
                contig: "NC_000001.11".to_string(),
                start: 100,
                bases: "TTTT".to_string(),
            }],
            ..Default::default()
        };
        serve_transcripts_whole(&mut fixture);
        let contigs: Vec<&str> = fixture.genomic.iter().map(|w| w.contig.as_str()).collect();
        assert_eq!(contigs, ["NC_000001.11", "NM_TEST.1"]);
    }
}
