//! Extract the hermetic reference slice behind the spec worked-examples gate.
//!
//! The twelve rows in `tests/fixtures/spec-worked-examples/cases.json` are the
//! spec's own published normalization answers, and every one of them is
//! sequence-dependent — repeat typing reads the tract, the 3'rule reads the
//! bases it would shift over. That means they cannot run under `MockProvider`,
//! and running them under the prepared reference would make them a
//! manifest-or-skip test that CI silently skips. So the same pattern the other
//! hermetic gates use applies here: run the real pass against a real manifest
//! through a [`RecordingProvider`], and commit precisely the slice it touched.
//!
//! Mirrors `extract_spec_enumeration_windows.rs` — same recorder, same padded
//! window merging, same "committed and reviewed, never regenerated in CI"
//! contract. `--check` is a *local* guard: run against the same manifest, it
//! fails if the committed slice no longer matches a fresh extraction.
//!
//! Unlike the enumeration slice, this one keeps its bases inline in the JSON
//! (like `tests/fixtures/biocommons-normalize/reference-windows.json`): two
//! transcripts of ~20 kb total is small enough that a sidecar split would cost
//! more in indirection than it saves in reviewability.
//!
//! Run:   `cargo run --features dev --example extract_spec_worked_example_windows -- --manifest PATH`
//! Check: `cargo run --features dev --example extract_spec_worked_example_windows -- --check`

use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::sync::Arc;

use clap::Parser;
use ferro_hgvs::conformance::spec_worked_examples::{Fixture, CASES_PATH, WINDOWS_PATH};
use ferro_hgvs::{parse_hgvs, MultiFastaProvider, Normalizer};

#[path = "common/recording.rs"]
mod recording;

use recording::{build_window_fixture, RecordingProvider};

#[derive(Parser, Debug)]
#[command(about = "Extract the hermetic reference slice for the spec worked-examples gate")]
struct Cli {
    /// Prepared-reference manifest. Falls back to `$FERRO_MANIFEST`.
    #[arg(long)]
    manifest: Option<PathBuf>,
    /// Compare the committed slice to a fresh extraction; exit non-zero on
    /// drift and write nothing. Requires the manifest.
    #[arg(long)]
    check: bool,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: &Cli) -> anyhow::Result<ExitCode> {
    let Some(manifest) = cli
        .manifest
        .clone()
        .or_else(|| std::env::var("FERRO_MANIFEST").ok().map(PathBuf::from))
    else {
        eprintln!("no manifest (pass --manifest or set FERRO_MANIFEST); cannot extract windows");
        return Ok(ExitCode::FAILURE);
    };

    let cases = Fixture::from_json_path(Path::new(CASES_PATH))
        .map_err(|e| anyhow::anyhow!("load {CASES_PATH}: {e}"))?;

    let provider = Arc::new(
        MultiFastaProvider::from_manifest(&manifest)
            .map_err(|e| anyhow::anyhow!("load manifest {}: {e}", manifest.display()))?,
    );
    let recorder = RecordingProvider::new(Arc::clone(&provider));
    let normalizer = Normalizer::new(recorder.clone());

    for case in &cases.cases {
        // A row that errors still recorded whatever it read, which is all this
        // pass is for. The gate itself is where an error is a failure.
        let variant = parse_hgvs(&case.input)
            .map_err(|e| anyhow::anyhow!("case {:?} does not parse: {e}", case.input))?;
        if let Err(e) = normalizer.normalize(&variant) {
            eprintln!("  note: {} did not normalize ({e})", case.input);
        }
    }

    // Record only the manifest's file name: an absolute path would leak the
    // local layout into the repo and churn `--check` per machine.
    let captured_from = manifest
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "manifest.json".to_string());
    let description = format!(
        "GENERATED by `cargo run --features dev --example extract_spec_worked_example_windows`. \
         Hermetic reference slice for the spec worked-examples gate: every transcript and padded \
         genomic window the normalize pass over cases.json touches. Do not hand-edit; regenerate \
         from a prepared-reference manifest. Margin: {} bp.",
        recording::PAD
    );

    // mRNA-sized records only. An `NG_`/`LRG_` genomic record resolved as a
    // "transcript" carries hundreds of KB of sequence; it is served through its
    // captured placement instead.
    let fixture = build_window_fixture(&recorder, captured_from, description, |tx| {
        tx.id.starts_with("NM_") || tx.id.starts_with("NR_") || is_lrg_transcript(&tx.id)
    });
    let rendered = fixture
        .to_json()
        .map_err(|e| anyhow::anyhow!("serialize fixture: {e}"))?;

    if cli.check {
        let committed = std::fs::read_to_string(WINDOWS_PATH).unwrap_or_default();
        if committed != rendered {
            eprintln!(
                "{WINDOWS_PATH} is OUT OF DATE — regenerate with `cargo run --features dev \
                 --example extract_spec_worked_example_windows -- --manifest <manifest>`."
            );
            return Ok(ExitCode::FAILURE);
        }
        println!(
            "committed reference slice is up to date ({} rows).",
            cases.cases.len()
        );
        return Ok(ExitCode::SUCCESS);
    }

    std::fs::write(WINDOWS_PATH, rendered)
        .map_err(|e| anyhow::anyhow!("write {WINDOWS_PATH}: {e}"))?;
    println!(
        "Wrote {WINDOWS_PATH}: {} transcripts, {} windows, {} placements (from {} rows).",
        fixture.transcripts.len(),
        fixture.genomic.len(),
        fixture.placements.len(),
        cases.cases.len()
    );
    Ok(ExitCode::SUCCESS)
}

/// Is `id` an LRG **transcript** record (`LRG_199t1`) rather than the LRG
/// genomic record (`LRG_199`)? Only the former is mRNA-sized.
fn is_lrg_transcript(id: &str) -> bool {
    let Some(rest) = id.strip_prefix("LRG_") else {
        return false;
    };
    match rest.split_once('t') {
        Some((num, tx)) => {
            !num.is_empty()
                && num.bytes().all(|b| b.is_ascii_digit())
                && !tx.is_empty()
                && tx.bytes().all(|b| b.is_ascii_digit())
        }
        None => false,
    }
}
