//! Spec clause -> the adjudication record(s) that already govern it.
//!
//! # The failure mode this exists for
//!
//! The single most-repeated mistake in this project's history is re-deriving a
//! *settled* question from spec text. Someone opens `DNA/delins.md`, reads
//! `:17`, forms a view, and acts on it — and the ledger has had an answer for
//! that clause the whole time. `delins.md:17` against `:47` has gone round at
//! least four times on exactly that path.
//!
//! `ruling_citation_currency.rs` catches the reverse direction: prose that
//! claims a settled record is still an open question. It cannot catch this one,
//! because the person who never looked the record up writes no citation for it
//! to check. What is missing is a way to get **from a clause to the record**,
//! and that is what this file is.
//!
//! # Where the index lives, and why here
//!
//! The rendered index is in this module's docs, below, and is regenerated by
//! [`the_rendered_index_is_current`] — the test fails with the exact block to
//! paste whenever the ledger moves. Two reasons for a doc comment rather than a
//! generated file under `tests/fixtures/`:
//!
//! * a generated fixture would be gitignored like the other generated spec
//!   artifacts, and a gitignored artifact has no committed baseline to drift
//!   from, so it could not be a guard at all — only a `--check` gate over a
//!   *committed* artifact would work, and that is a second copy of this text
//!   with the same maintenance cost and less chance of being read;
//! * the reader this is for is holding a clause string, and a clause string is
//!   greppable from the repo root:
//!
//! ```text
//! grep -n 'delins.md:47' tests/it/clause_ruling_index.rs
//! ```
//!
//! **State the limit honestly**: this is a floor, not a solution. The person
//! reading `assets/hgvs-nomenclature/docs/recommendations/DNA/delins.md` gets no
//! signal at the point of reading. The submodule is upstream's checkout, so
//! nothing may be written into it; a repo-side index that a `grep` finds is the
//! best available placement, and the tests below are what keep it true.
//!
//! # Ranges: every citation is indexed per line
//!
//! The ledger spells some citations as ranges (`…/DNA/delins.md:79-84`,
//! `…/consultation/open-issues.md:77-78`) and others as single lines. Someone
//! who looked up `open-issues.md:78` must find the record that cites
//! `open-issues.md:77-78`, and vice versa, so **the index key is a single
//! `file:line`** and a range citation is expanded into one entry per line it
//! covers. The record's own spelling is preserved in the entry (`via
//! …:77-78`), so nothing is lost by the expansion.
//!
//! That is not hypothetical: `open-issues.md:78` is currently reached by an
//! exact citation from one record and by a range citation from another, and
//! those two records disagree in status. A file-granular or spelling-granular
//! index would have shown them as unrelated.
//!
//! # Counts measured on this base
//!
//! **Read them off the generated index below, not from this paragraph.** The
//! header line of that block is regenerated from the ledger, and
//! [`the_index_is_not_vacuous`] pins the same figures, so both move together and
//! neither can be quietly restated.
//!
//! This paragraph used to carry the numbers itself — "14 records, 9 decided /
//! 5 undecided … was 10 / 6 / 4" — and went stale the moment the branch rebased
//! onto a `main` that had gained a record, while the generated block three
//! screens down regenerated correctly and disagreed with it. That is the exact
//! failure the pin was added to prevent, reproduced in the prose that describes
//! the pin: the repo's own `CLAUDE.md` carried "five of its eight" long after
//! the ledger passed eight. A number worth trusting is a measured one, so the
//! fix is to stop keeping a second copy rather than to pin the copy.
//!
//! A delta was supposed to be the durable form, and this paragraph proves it is
//! not: it listed the four refusal-class records this branch once contributed
//! (`alignment-only-symbol-in-a-description`,
//! `bare-transcript-intronic-position`,
//! `conflicting-member-geometry-refusal-scope`,
//! `absolute-prohibition-enforcement-stage`) and went stale anyway, because all
//! four have since landed on `main` and are now in the base rather than in the
//! delta. A delta does not go stale when the base moves *underneath* it; it goes
//! stale when the base moves *past* it. Both records that paragraph then named
//! as this branch's delta — `contiguous-insertion-split-by-a-blocked-derivation`
//! and `delins-recommendation-reach-when-the-input-arrives-split` — have landed
//! on `main` in their turn and are now base as well, which is the same rot a
//! second time. Measured against the merge base, what this branch adds is one
//! record:
//!
//! - `rna-axis-alignment-only-symbol-reach` — ruled 2026-08-12 (#1715), with
//!   `docs/background/standards.md:47-61` governing
//!
//! This paragraph used to predict that the pins below "will move once more on
//! the next rebase", naming `codon-carve-out-shape-restriction` and
//! `exon-junction-dup-converge-from-the-far-side` as records `main` had decided
//! while this tree still carried them as `undecided`. That was already false
//! when it was written — both read `decided` here too — and the rebase has since
//! settled the question: measured against current `main`, **no** record is
//! `decided` there and `undecided` here. The prediction is gone rather than
//! refreshed, for the reason the sibling module states about restated counts: a
//! forecast about a moving base is a copy of someone else's state, and it rots
//! exactly like a copied number does.
//!
//! # The index
//!
//! <!-- BEGIN GENERATED INDEX -->
//! ```text
//! CLAUSE -> RECORD INDEX
//! 24 records, 21 decided / 3 undecided
//! 99 clause lines, of which 26 are named by more than one record
//!
//! == every clause line ==
//!
//! docs/background/basics.md:38  [MULTI]
//!     `adjudication-precedence-order` — decided (cited)
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/background/standards.md:36  [MULTI]
//!     `alignment-only-symbol-in-a-description` — decided (cited)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/background/standards.md:37
//!     `alignment-only-symbol-in-a-description` — decided (cited)
//! docs/background/standards.md:39  [MULTI]
//!     `alignment-only-symbol-in-a-description` — decided (governing)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/background/standards.md:47
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:48
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:49
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:50
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:51
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:52
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:53
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:54
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:55
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:56
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:57
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:58
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:59
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:60
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/background/standards.md:61
//!     `rna-axis-alignment-only-symbol-reach` — decided (governing, via docs/background/standards.md:47-61)
//! docs/consultation/SVD-WG010.md:5  [MULTI]
//!     `delins-codon-carve-out-gap-one` — decided (cited)
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/consultation/SVD-WG010.md:16
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/consultation/open-issues.md:77  [MULTI]
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited, via docs/consultation/open-issues.md:77-78)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited, via docs/consultation/open-issues.md:77-78)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited, via docs/consultation/open-issues.md:77-78)
//! docs/consultation/open-issues.md:78  [MULTI]
//!     `adjudication-precedence-order` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited, via docs/consultation/open-issues.md:77-78)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited, via docs/consultation/open-issues.md:77-78)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited, via docs/consultation/open-issues.md:77-78)
//! docs/recommendations/DNA/alleles.md:5
//!     `conflicting-member-geometry-refusal-scope` — decided (governing)
//! docs/recommendations/DNA/complex.md:5
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:13
//!     `ring-telomere-anchoring` — undecided (cited)
//! docs/recommendations/DNA/complex.md:28
//!     `ring-telomere-anchoring` — undecided (cited)
//! docs/recommendations/DNA/complex.md:39
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:50
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//! docs/recommendations/DNA/complex.md:51
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:53
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:55
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:63
//!     `adjudication-precedence-order` — decided (governing)
//! docs/recommendations/DNA/complex.md:64
//!     `adjudication-precedence-order` — decided (cited)
//! docs/recommendations/DNA/complex.md:113
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:117
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:127  [MULTI]
//!     `ring-telomere-anchoring` — undecided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:130
//!     `self-cancelling-across-ring-junctions` — decided (governing)
//! docs/recommendations/DNA/complex.md:161  [MULTI]
//!     `ring-telomere-anchoring` — undecided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/delins.md:15
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/recommendations/DNA/delins.md:16  [MULTI]
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/recommendations/DNA/delins.md:17  [MULTI]
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/DNA/delins.md:18  [MULTI]
//!     `codon-carve-out-shape-restriction` — decided (governing)
//!     `delins-codon-carve-out-gap-one` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/DNA/delins.md:42
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (governing)
//! docs/recommendations/DNA/delins.md:46
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/recommendations/DNA/delins.md:47  [MULTI]
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (governing)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (governing)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/DNA/delins.md:79
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:80
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:81  [MULTI]
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//!     `separation-rule-force-modal-or-negation` — decided (governing)
//! docs/recommendations/DNA/delins.md:82
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:83  [MULTI]
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:84
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:86
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//! docs/recommendations/DNA/delins.md:88
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//! docs/recommendations/DNA/delins.md:89  [MULTI]
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/recommendations/DNA/duplication.md:18  [MULTI]
//!     `codon-carve-out-shape-restriction` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/DNA/duplication.md:26
//!     `exon-junction-dup-converge-from-the-far-side` — decided (governing)
//! docs/recommendations/DNA/duplication.md:60
//!     `exon-junction-dup-converge-from-the-far-side` — decided (cited)
//! docs/recommendations/DNA/duplication.md:90
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/recommendations/DNA/duplication.md:91
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/recommendations/DNA/duplication.md:92
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/recommendations/DNA/duplication.md:148  [MULTI]
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited)
//!     `exon-junction-dup-converge-from-the-far-side` — decided (cited)
//! docs/recommendations/DNA/inversion.md:5
//!     `inversion-vs-two-delins-76-83` — decided (governing)
//! docs/recommendations/DNA/inversion.md:33
//!     `inversion-vs-two-delins-76-83` — decided (cited, via docs/recommendations/DNA/inversion.md:33-34)
//! docs/recommendations/DNA/inversion.md:34
//!     `inversion-vs-two-delins-76-83` — decided (cited, via docs/recommendations/DNA/inversion.md:33-34)
//! docs/recommendations/DNA/repeated.md:23
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//! docs/recommendations/DNA/substitution.md:16
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/DNA/substitution.md:32  [MULTI]
//!     `delins-adjacent-members-when-both-consume-reference` — decided (governing)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/DNA/substitution.md:95
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//! docs/recommendations/RNA/delins.md:18
//!     `delins-codon-carve-out-gap-one` — decided (cited)
//! docs/recommendations/RNA/delins.md:41
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//! docs/recommendations/RNA/delins.md:70
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//! docs/recommendations/RNA/repeated.md:20
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited, via docs/recommendations/RNA/repeated.md:20-21)
//! docs/recommendations/RNA/repeated.md:21
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited, via docs/recommendations/RNA/repeated.md:20-21)
//! docs/recommendations/RNA/repeated.md:22
//!     `rna-repeat-range-plus-unit-redundancy` — undecided (cited)
//! docs/recommendations/RNA/repeated.md:27
//!     `rna-repeat-range-plus-unit-redundancy` — undecided (cited)
//! docs/recommendations/RNA/substitution.md:18
//!     `delins-codon-carve-out-gap-one` — decided (cited)
//! docs/recommendations/checklist.md:5
//!     `absolute-prohibition-enforcement-stage` — decided (governing)
//! docs/recommendations/checklist.md:16
//!     `absolute-prohibition-enforcement-stage` — decided (cited)
//! docs/recommendations/checklist.md:20
//!     `bare-transcript-intronic-position` — decided (governing)
//! docs/recommendations/checklist.md:31
//!     `absolute-prohibition-enforcement-stage` — decided (cited)
//! docs/recommendations/checklist.md:33
//!     `absolute-prohibition-enforcement-stage` — decided (cited)
//! docs/recommendations/checklist.md:45
//!     `bare-transcript-intronic-position` — decided (cited)
//! docs/recommendations/general.md:23
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:26
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:34  [MULTI]
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (governing)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (governing)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/general.md:35
//!     `codon-carve-out-shape-restriction` — decided (cited)
//! docs/recommendations/general.md:39
//!     `delins-codon-carve-out-gap-one` — decided (cited)
//! docs/recommendations/general.md:41  [MULTI]
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/general.md:43  [MULTI]
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:44  [MULTI]
//!     `bare-transcript-intronic-position` — decided (cited)
//!     `exon-junction-dup-converge-from-the-far-side` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:48  [MULTI]
//!     `alignment-only-symbol-in-a-description` — decided (cited)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/recommendations/general.md:50
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/recommendations/general.md:56  [MULTI]
//!     `adjudication-precedence-order` — decided (cited)
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (deviates-from)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/general.md:58  [MULTI]
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/general.md:157
//!     `canonical-form-choice-when-both-legal` — decided (governing)
//! docs/recommendations/protein/delins.md:50
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//! docs/recommendations/style.md:9  [MULTI]
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//! docs/versions/index.md:16
//!     `adjudication-precedence-order` — decided (cited)
//!
//! == clause lines named by more than one record ==
//!
//! -- mixed verdicts: at least one settled record and at least one still an --
//! -- unanswered question on the same line. This is where re-derivation from --
//! -- the spec text actually happens; read BOTH records before forming a view. --
//!
//! docs/consultation/open-issues.md:77
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited, via docs/consultation/open-issues.md:77-78)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited, via docs/consultation/open-issues.md:77-78)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited, via docs/consultation/open-issues.md:77-78)
//! docs/consultation/open-issues.md:78
//!     `adjudication-precedence-order` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited, via docs/consultation/open-issues.md:77-78)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited, via docs/consultation/open-issues.md:77-78)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited, via docs/consultation/open-issues.md:77-78)
//! docs/recommendations/DNA/complex.md:127
//!     `ring-telomere-anchoring` — undecided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/complex.md:161
//!     `ring-telomere-anchoring` — undecided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/DNA/delins.md:17
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/DNA/delins.md:47
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (governing)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (governing)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/general.md:34
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (governing)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `delins-recommendation-reach-when-the-input-arrives-split` — undecided (cited)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (governing)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//!
//! -- same verdict across every record naming the line --
//!
//! docs/background/basics.md:38
//!     `adjudication-precedence-order` — decided (cited)
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/background/standards.md:36
//!     `alignment-only-symbol-in-a-description` — decided (cited)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/background/standards.md:39
//!     `alignment-only-symbol-in-a-description` — decided (governing)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/consultation/SVD-WG010.md:5
//!     `delins-codon-carve-out-gap-one` — decided (cited)
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//! docs/recommendations/DNA/delins.md:16
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/recommendations/DNA/delins.md:18
//!     `codon-carve-out-shape-restriction` — decided (governing)
//!     `delins-codon-carve-out-gap-one` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/DNA/delins.md:81
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//!     `separation-rule-force-modal-or-negation` — decided (governing)
//! docs/recommendations/DNA/delins.md:83
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (deviates-from, via docs/recommendations/DNA/delins.md:79-84)
//! docs/recommendations/DNA/delins.md:89
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//! docs/recommendations/DNA/duplication.md:18
//!     `codon-carve-out-shape-restriction` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (cited)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/DNA/duplication.md:148
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (cited)
//!     `exon-junction-dup-converge-from-the-far-side` — decided (cited)
//! docs/recommendations/DNA/substitution.md:32
//!     `delins-adjacent-members-when-both-consume-reference` — decided (governing)
//!     `separation-rule-force-modal-or-negation` — decided (cited)
//! docs/recommendations/general.md:41
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `separation-is-a-property-of-the-spelling-not-of-the-variant` — decided (cited)
//! docs/recommendations/general.md:43
//!     `confluence-gate-is-apply-equality-on-every-determined-axis` — decided (governing)
//!     `delins-payload-coincidence-carve-out-is-coding-dna-scoped` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:44
//!     `bare-transcript-intronic-position` — decided (cited)
//!     `exon-junction-dup-converge-from-the-far-side` — decided (cited)
//!     `projection-codon-exception-is-decided-by-the-rendered-axis` — decided (cited)
//! docs/recommendations/general.md:48
//!     `alignment-only-symbol-in-a-description` — decided (cited)
//!     `rna-axis-alignment-only-symbol-reach` — decided (cited)
//! docs/recommendations/general.md:56
//!     `adjudication-precedence-order` — decided (cited)
//!     `canonical-form-choice-when-both-legal` — decided (cited)
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `contiguous-insertion-split-by-a-blocked-derivation` — decided (cited)
//!     `delins-adjacent-members-when-both-consume-reference` — decided (deviates-from)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/general.md:58
//!     `conflicting-member-geometry-refusal-scope` — decided (cited)
//!     `derivation-may-not-be-bounded-by-the-inputs-spelling` — decided (cited)
//!     `self-cancelling-across-ring-junctions` — decided (cited)
//! docs/recommendations/style.md:9
//!     `delins-merge-vs-individual-gap-two-or-more` — decided (cited)
//!     `inversion-vs-two-delins-76-83` — decided (cited)
//! ```
//! <!-- END GENERATED INDEX -->
//!
//! # Reading the mixed-verdict block
//!
//! **Most multiply-named lines carry mixed verdicts** — the counts are in the
//! generated block above and pinned by [`clauses_named_by_several_records_are_flagged`],
//! and are deliberately not restated here. They were, as "six of the nine", and
//! the rebase that added a record made that wrong in both halves while the
//! generated block regenerated correctly; the test's own failure message even
//! says "update the module docs with it", which is a rule that only fires when
//! the measured number moves *and* someone re-reads prose the test does not
//! check.
//!
//! What is worth saying in prose is which row matters, and that the mixed count
//! moves in **both** directions: it falls as records get *decided*, and it rises
//! as an open question is filed against a line that settled records already
//! name. This paragraph asserted only the first half, and the second half is
//! what actually happened next — filing one `undecided` record,
//! `delins-recommendation-reach-when-the-input-arrives-split`, moved five lines
//! out of the same-verdict block and into the mixed one at a stroke
//! (`open-issues.md:77`, `:78`, `delins.md:17`, `:47`, `general.md:34` — every
//! line that record cites).
//!
//! `delins.md:17` is the row this project keeps tripping over, and it is a good
//! illustration precisely because it has now been on both sides. It was mixed;
//! it left the mixed block when
//! `separation-is-a-property-of-the-spelling-not-of-the-variant` was decided,
//! resolving to two settled records whose *scopes* differ — which is its own way
//! of being half-wrong when read from one of them alone; and the delins-reach
//! question put it back. So neither leaving nor entering the mixed block says
//! anything about whether the line is safe to read from a single record. The
//! index does not adjudicate anything — it only tells you that more than one
//! record is in play, which is the fact that was missing.
//!
//! `DNA/complex.md:127` and `:161` joined that set when the ring rules landed:
//! they are the spec's two published ring shapes — the bare ring and the
//! supernumerary one — and each is cited both by
//! `self-cancelling-across-ring-junctions` (**decided**) and by
//! `ring-telomere-anchoring` (**undecided**). That split is the honest state —
//! the same examples settle one question about rings and are merely suggestive
//! about another — and it is the case this block exists to surface, since citing
//! either for "rings are anchored" would read a ruling out of the undecided half.
//!
//! The same-verdict lines are a much weaker signal: they are the clauses cited
//! as background in nearly every conflict — `basics.md:38`, `general.md:41`,
//! `general.md:56`, `general.md:58` and `style.md:9`. (That list is a *set*, not
//! a count, so it stays checkable by inspection; it previously omitted
//! `general.md:58`, and then `general.md:41`, which
//! `contiguous-insertion-split-by-a-blocked-derivation` added to the set.)
//!
//! # Sibling
//!
//! `tests/it/ruling_citation_currency.rs` — the reverse direction, and the
//! source of the shared ledger reader both files use
//! (`tests/it/common/rulings.rs`).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::common::rulings;

/// This file, relative to the crate root — read back by
/// [`the_rendered_index_is_current`].
const SELF_RELATIVE_PATH: &str = "tests/it/clause_ruling_index.rs";

const BEGIN_MARKER: &str = "<!-- BEGIN GENERATED INDEX -->";
const END_MARKER: &str = "<!-- END GENERATED INDEX -->";

/// Refuses a citation whose range is implausibly wide.
///
/// A typo (`:5-500`) would otherwise silently expand into hundreds of index
/// keys and bury the real ones. No real citation is anywhere near this.
const MAX_RANGE_LINES: u32 = 64;

/// An index key: one spec file and one line in it.
///
/// Ordering is `(file, line)` with the line compared numerically, so
/// `duplication.md:26` sorts before `duplication.md:148` rather than after it.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
struct ClauseLine {
    file: String,
    line: u32,
}

impl std::fmt::Display for ClauseLine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}:{}", self.file, self.line)
    }
}

/// One record's claim on one clause line.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
struct Claim {
    /// Sorted first so a clause line's records render alphabetically.
    id: String,
    status: String,
    role_label: &'static str,
    /// The record's own spelling, kept only when it differs from the key —
    /// i.e. when the citation was a range.
    via: Option<String>,
}

/// Expand one citation into the clause lines it covers.
///
/// `…/delins.md:47` yields one; `…/delins.md:79-84` yields six. The record's
/// spelling is returned alongside so the caller can annotate range-derived
/// entries.
fn expand(clause: &str) -> Vec<ClauseLine> {
    let (file, locator) = clause
        .rsplit_once(':')
        .unwrap_or_else(|| panic!("citation {clause} has no `:<line>` locator"));
    let parse = |s: &str| -> u32 {
        s.parse()
            .unwrap_or_else(|e| panic!("citation {clause}: `{s}` is not a line number: {e}"))
    };
    let (first, last) = match locator.split_once('-') {
        Some((first, last)) => (parse(first), parse(last)),
        None => {
            let only = parse(locator);
            (only, only)
        }
    };
    assert!(
        first > 0,
        "citation {clause} names line 0; source lines are 1-based, so no file carries it — and \
         both checks below accept it, since 0 <= 0 and a zero-width span is under the limit"
    );
    assert!(
        first <= last,
        "citation {clause} runs backwards ({first} > {last})"
    );
    assert!(
        last - first < MAX_RANGE_LINES,
        "citation {clause} spans {} lines, more than the {MAX_RANGE_LINES}-line sanity limit — \
         a range that wide is almost certainly a typo and would bury the rest of the index",
        last - first + 1
    );
    (first..=last)
        .map(|line| ClauseLine {
            file: file.to_string(),
            line,
        })
        .collect()
}

/// The whole index: clause line -> every record naming it.
fn build_index() -> BTreeMap<ClauseLine, BTreeSet<Claim>> {
    let mut index: BTreeMap<ClauseLine, BTreeSet<Claim>> = BTreeMap::new();
    for record in rulings::records() {
        for citation in &record.citations {
            let keys = expand(&citation.clause);
            let is_range = keys.len() > 1;
            for key in keys {
                index.entry(key).or_default().insert(Claim {
                    id: record.id.clone(),
                    status: record.status.clone(),
                    role_label: citation.role.label(),
                    via: is_range.then(|| citation.clause.clone()),
                });
            }
        }
    }
    index
}

/// One rendered `    \`id\` — status (role)` line.
///
/// Each claim gets its own line, and that is load-bearing rather than
/// cosmetic: `ruling_citation_currency.rs` judges a status word against every
/// record id on the *same* line, so putting two records with different statuses
/// on one line would make this file fail that scan.
fn render_claim(claim: &Claim) -> String {
    let via = match &claim.via {
        Some(clause) => format!(", via {clause}"),
        None => String::new(),
    };
    format!(
        "    `{}` — {} ({}{via})",
        claim.id, claim.status, claim.role_label
    )
}

fn render_entry(out: &mut String, key: &ClauseLine, claims: &BTreeSet<Claim>, mark_multi: bool) {
    let marker = if mark_multi && claims.len() > 1 {
        "  [MULTI]"
    } else {
        ""
    };
    let _ = writeln!(out, "{key}{marker}");
    for claim in claims {
        let _ = writeln!(out, "{}", render_claim(claim));
    }
}

/// The whole index as the text embedded in this module's docs.
fn render_index() -> String {
    let index = build_index();
    let records = rulings::records();
    let decided = records.iter().filter(|r| r.status == "decided").count();
    let undecided = records.len() - decided;
    let multi: Vec<(&ClauseLine, &BTreeSet<Claim>)> =
        index.iter().filter(|(_, c)| c.len() > 1).collect();

    let mut out = String::new();
    let _ = writeln!(out, "CLAUSE -> RECORD INDEX");
    let _ = writeln!(
        out,
        "{} records, {decided} decided / {undecided} undecided",
        records.len()
    );
    let _ = writeln!(
        out,
        "{} clause lines, of which {} are named by more than one record",
        index.len(),
        multi.len()
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "== every clause line ==");
    let _ = writeln!(out);
    for (key, claims) in &index {
        render_entry(&mut out, key, claims, true);
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "== clause lines named by more than one record ==");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "-- mixed verdicts: at least one settled record and at least one still an --"
    );
    let _ = writeln!(
        out,
        "-- unanswered question on the same line. This is where re-derivation from --"
    );
    let _ = writeln!(
        out,
        "-- the spec text actually happens; read BOTH records before forming a view. --"
    );
    let _ = writeln!(out);
    let mixed = |claims: &BTreeSet<Claim>| {
        claims
            .iter()
            .map(|c| &c.status)
            .collect::<BTreeSet<_>>()
            .len()
            > 1
    };
    for (key, claims) in multi.iter().filter(|(_, c)| mixed(c)) {
        render_entry(&mut out, key, claims, false);
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "-- same verdict across every record naming the line --"
    );
    let _ = writeln!(out);
    for (key, claims) in multi.iter().filter(|(_, c)| !mixed(c)) {
        render_entry(&mut out, key, claims, false);
    }
    out
}

/// The index block currently embedded in this module's docs.
fn embedded_index() -> String {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(SELF_RELATIVE_PATH);
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut inside = false;
    let mut block = String::new();
    for line in text.lines() {
        if line.contains(BEGIN_MARKER) {
            inside = true;
            continue;
        }
        if line.contains(END_MARKER) {
            inside = false;
            continue;
        }
        if !inside {
            continue;
        }
        let stripped = line.strip_prefix("//! ").unwrap_or(
            line.strip_prefix("//!")
                .unwrap_or_else(|| panic!("index block line is not a doc comment: {line}")),
        );
        // The block is wrapped in a `text` fence so rustdoc does not try to
        // compile or link it; the fences are not part of the index.
        if stripped.trim_start().starts_with("```") {
            continue;
        }
        block.push_str(stripped);
        block.push('\n');
    }
    block
}

/// The scan is not vacuous, and the counts are the measured ones.
///
/// Modelled on `ruling_citation_currency.rs`'s
/// `the_scan_reads_the_tree_it_claims_to`: an index built from a ledger that
/// failed to parse, or an expander that dropped every citation, would otherwise
/// make every assertion below pass trivially.
#[test]
fn the_index_is_not_vacuous() {
    let records = rulings::records();
    let decided = records.iter().filter(|r| r.status == "decided").count();
    let undecided = records.iter().filter(|r| r.status == "undecided").count();
    assert_eq!(
        (records.len(), decided, undecided),
        (24, 21, 3),
        "measured ledger census changed. If this is a real ledger change, update the module docs \
         and this pin together. Note the repo `CLAUDE.md` claims 8 records with 5 unanswered, \
         which was already wrong before this test existed"
    );
    assert_eq!(
        decided + undecided,
        records.len(),
        "a record carries a status that is neither `decided` nor `undecided`"
    );

    let index = build_index();
    assert!(
        index.len() >= 30,
        "only {} clause lines indexed — the expander or the ledger reader is broken",
        index.len()
    );
    // Every record must reach the index, or the inversion lost one.
    let indexed_ids: BTreeSet<&String> = index.values().flatten().map(|c| &c.id).collect();
    assert_eq!(
        indexed_ids.len(),
        records.len(),
        "{} of {} records reached the index",
        indexed_ids.len(),
        records.len()
    );
    // And the range expander must have actually expanded something, or the
    // range-handling contract in the module docs is untested.
    let via_range = index.values().flatten().filter(|c| c.via.is_some()).count();
    assert!(
        via_range > 0,
        "no range citation was expanded — the file-vs-line contract in this module's docs is \
         vacuous on this ledger"
    );
}

/// The expander handles the two spellings the ledger uses, including the case
/// the module docs promise: a line reachable both exactly and through a range.
#[test]
fn a_range_citation_is_findable_by_any_line_it_covers() {
    assert_eq!(
        expand("docs/recommendations/DNA/delins.md:47"),
        vec![ClauseLine {
            file: "docs/recommendations/DNA/delins.md".to_string(),
            line: 47
        }]
    );
    let range = expand("docs/recommendations/DNA/delins.md:44-47");
    assert_eq!(range.len(), 4, "44-47 covers four lines");
    assert!(
        range.contains(&ClauseLine {
            file: "docs/recommendations/DNA/delins.md".to_string(),
            line: 47
        }),
        "someone who looked up `delins.md:47` must find a record citing `delins.md:44-47`"
    );

    // The live instance of the same thing, in the committed ledger: one line
    // reached by an exact citation from one record and a range from another.
    let index = build_index();
    let key = ClauseLine {
        file: "docs/consultation/open-issues.md".to_string(),
        line: 78,
    };
    let claims = index
        .get(&key)
        .unwrap_or_else(|| panic!("{key} is not in the index"));
    assert!(
        claims.iter().any(|c| c.via.is_none()) && claims.iter().any(|c| c.via.is_some()),
        "{key} should be reached both exactly and through a range: {claims:?}"
    );
}

/// A line-0 locator is rejected rather than expanded.
///
/// It slips past both of the expander's other guards — `0 <= 0` holds and a
/// zero-width span is inside the sanity limit — so without its own check it
/// would enter the index as a key no file can carry, and the completeness
/// assertion would happily confirm it round-trips.
#[test]
#[should_panic(expected = "names line 0")]
fn a_zero_line_locator_is_rejected() {
    expand("docs/recommendations/DNA/delins.md:0");
}

/// The same for the low end of a range.
#[test]
#[should_panic(expected = "names line 0")]
fn a_range_starting_at_line_zero_is_rejected() {
    expand("docs/recommendations/DNA/delins.md:0-4");
}

/// **Completeness.** Every clause named by every record is in the index, under
/// every line it covers, carrying that record's id and status — and reaches the
/// **embedded artifact**, not only the in-memory map.
///
/// This is the assertion the file exists to make: a record whose clause the
/// index misses is a clause a reader can look up and be told nothing about.
///
/// The second half is what keeps the first from being circular. Checking
/// `build_index()` against the same `expand()` over the same records can only
/// catch a bug in the insertion — a key collapsed, a claim overwritten. It says
/// nothing about what a human actually sees. So each key is also required to
/// appear in the text embedded in this module's docs, which is the thing the
/// `grep` in those docs will hit.
#[test]
fn every_cited_clause_appears_in_the_index() {
    let index = build_index();
    let embedded = embedded_index();
    let mut missing: Vec<String> = Vec::new();
    let mut unrendered: Vec<String> = Vec::new();
    for record in rulings::records() {
        for citation in &record.citations {
            for key in expand(&citation.clause) {
                let found = index.get(&key).is_some_and(|claims| {
                    claims
                        .iter()
                        .any(|c| c.id == record.id && c.status == record.status)
                });
                if !found {
                    missing.push(format!(
                        "{key} (cited as {} by {} / {})",
                        citation.clause, record.id, record.status
                    ));
                }
                let key_line = key.to_string();
                if !embedded
                    .lines()
                    .any(|l| l == key_line || l == format!("{key_line}  [MULTI]"))
                {
                    unrendered.push(key_line);
                }
            }
        }
    }
    assert!(
        missing.is_empty(),
        "these clause lines are named by a record but absent from the index:\n  {}\n\nfull index \
         as computed:\n{}",
        missing.join("\n  "),
        render_index()
    );
    assert!(
        unrendered.is_empty(),
        "these clause lines are in the computed index but not in the block embedded in this \
         module's docs, so a reader grepping for them finds nothing:\n  {}",
        unrendered.join("\n  ")
    );
}

/// **Multiply-named clauses are surfaced**, and the mixed-verdict ones are
/// called out separately.
///
/// The clause line below is the one this project has re-derived from spec text
/// at least four times; see `tests/it/delins_equal_vs_unequal_length_hermetic.rs`
/// for the pinned rows. It is asserted by name so that a ledger edit which drops
/// either record from it has to be argued rather than merged quietly.
#[test]
fn clauses_named_by_several_records_are_flagged() {
    let index = build_index();
    let multi: Vec<(&ClauseLine, &BTreeSet<Claim>)> =
        index.iter().filter(|(_, c)| c.len() > 1).collect();
    assert_eq!(
        multi.len(),
        26,
        "measured count of multiply-named clause lines changed; update the module docs with it"
    );

    let mixed: Vec<String> = multi
        .iter()
        .filter(|(_, claims)| {
            claims
                .iter()
                .map(|c| &c.status)
                .collect::<BTreeSet<_>>()
                .len()
                > 1
        })
        .map(|(key, _)| key.to_string())
        .collect();
    assert_eq!(
        mixed.len(),
        7,
        "measured count of mixed-verdict clause lines changed: {mixed:?}"
    );

    let key = ClauseLine {
        file: "docs/recommendations/DNA/delins.md".to_string(),
        line: 17,
    };
    let claims = index
        .get(&key)
        .unwrap_or_else(|| panic!("{key} is not in the index"));
    let ids: BTreeSet<&str> = claims.iter().map(|c| c.id.as_str()).collect();
    assert!(
        ids.contains("delins-merge-vs-individual-gap-two-or-more"),
        "{key} must resolve to the record that governs it: {ids:?}"
    );
    assert!(
        ids.contains("separation-is-a-property-of-the-spelling-not-of-the-variant"),
        "{key} must also resolve to the record that frames it as spelling-relative: {ids:?}"
    );

    // The canonical MIXED-verdict line has now moved twice, for the same reason
    // both times: the line stopped carrying a spread because the record that
    // supplied its `undecided` half got decided. `delins.md:17` lost it when
    // `separation-is-a-property-of-the-spelling-not-of-the-variant` was decided,
    // and `delins.md:18` lost it here, when `codon-carve-out-shape-restriction`
    // was. That is the expected direction of travel — the ledger is being burned
    // down — so this assertion is a moving target BY DESIGN and re-pointing it is
    // the correct maintenance, not a workaround.
    //
    // **The direction of travel is not monotonic, and `delins.md:17` is the
    // counter-example.** It is mixed AGAIN, because
    // `delins-recommendation-reach-when-the-input-arrives-split` was filed
    // against it (and against `:47`, and `general.md:34`, and
    // `open-issues.md:77-78`) as `undecided` — five lines gained a spread from
    // one new record, taking the measured `mixed` count from two to seven. So a
    // line can re-acquire a spread by a record being FILED, not only lose one by
    // a record being decided, and the burn-down framing above describes only the
    // decided half. Do not read a rise in this count as a regression: filing an
    // honest `undecided` record is what the ledger is for.
    //
    // It is pointed at a ring line rather than another `delins` one deliberately.
    // `complex.md:127` is cited by two records whose verdicts differ — and note
    // each is named on its own line below, because `ruling_citation_currency`
    // reads a status word and a record id sharing one line as a claim about that
    // record, so naming both verdicts beside both ids reads as a contradiction:
    //
    //   - `self-cancelling-across-ring-junctions` is decided.
    //   - `ring-telomere-anchoring` is undecided (added by #1595).
    //
    // That pair is the *reason* the mixed-verdict section exists — one clause
    // whose ring question is settled and whose anchoring question explicitly is
    // not. It is also the more durable choice: the two `delins` lines each had a
    // single open record standing between them and being settled, whereas
    // `ring-telomere-anchoring` is recorded as undecided on the grounds that
    // deciding it would legislate from two worked examples.
    //
    // If this fires again, the fix is to re-point it at whatever line the
    // measured `mixed` set above still contains — and if that set is ever EMPTY,
    // do not delete the assertion: an empty mixed-verdict section means the
    // rendering has nothing left to exercise, which is a fact worth failing on.
    let mixed_key = ClauseLine {
        file: "docs/recommendations/DNA/complex.md".to_string(),
        line: 127,
    };
    let mixed_claims = index
        .get(&mixed_key)
        .unwrap_or_else(|| panic!("{mixed_key} is not in the index"));
    assert!(
        mixed_claims
            .iter()
            .map(|c| &c.status)
            .collect::<BTreeSet<_>>()
            .len()
            > 1,
        "{mixed_key} is the canonical mixed-verdict clause line and must render in that section"
    );
}

/// The rendered index in this module's docs matches the ledger.
///
/// Failing prints the whole block to paste, so bringing it back into line is a
/// copy. The docs are the artifact a reader finds; a stale artifact is the same
/// failure this file is about, one level up.
#[test]
fn the_rendered_index_is_current() {
    let rendered = render_index();
    let embedded = embedded_index();
    assert!(
        !embedded.trim().is_empty(),
        "no index block found between the markers in {SELF_RELATIVE_PATH} — the extractor or the \
         markers moved"
    );
    if rendered.trim_end() != embedded.trim_end() {
        let block: String = rendered
            .lines()
            .map(|l| {
                if l.is_empty() {
                    "//!".to_string()
                } else {
                    format!("//! {l}")
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "the index in this module's docs is stale. Replace everything between\n  \
             {BEGIN_MARKER}\nand\n  {END_MARKER}\n(keeping the ```text fences) with:\n\n{block}\n"
        );
    }
}
