//! The real-world multi-member cis alleles, as an axis (#1443, part 1).
//!
//! `canonicalize_from_sequence` is gated on `members.len() > 1`, so a
//! single-member input never reaches the partitioner, the changed-column bound
//! or the member-ordering rules. `examples/harvest_multi_member_cis.rs` swept
//! all four bulk corpora for inputs that do: **592 out of 9 949 738 rows**.
//! Those 592 are the entire real-world evidence base for that code path, and
//! before this module they lived only inside Git-LFS corpora whose test suites
//! *skip green* when the fixtures are absent — so on a checkout without LFS the
//! evidence was silently invisible.
//!
//! The harvested fixture is committed, so this module runs everywhere.
//!
//! # Two tiers
//!
//! 1. **Always on.** Every row parses, and the distributions — members per
//!    allele, and the gap between consecutive members — are pinned. This is a
//!    description of what consumers of *observed* variants actually submit, and
//!    it is the number that motivates the generated corpus in
//!    `cis_confluence_axis`: separations are overwhelmingly large, which is
//!    exactly why real data cannot exercise a partitioner.
//! 2. **Manifest-gated** (`FERRO_MANIFEST`, or `benchmark-output/manifest.json`;
//!    skipped with a message when neither is present, the same convention
//!    `biocommons_normalize_tests` uses). Normalizes every row against real
//!    reference data and checks idempotence and sequence preservation, then
//!    censuses how often the spanning-`delins` respelling of a row converges to
//!    the same output.
//!
//! # Why the respelling census is a census
//!
//! Confluence over real rows does not hold today. Pinning the numbers documents
//! where it stands; asserting perfection would just leave the suite red. The
//! target is total convergence and the pinned figures must only move towards
//! it — the same contract `cis_confluence_axis` states at greater length.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::Deserialize;

use ferro_hgvs::spdi::hgvs_to_spdi;
use ferro_hgvs::{
    parse_hgvs, HgvsVariant, MultiFastaProvider, NormalizeConfig, Normalizer, ReferenceProvider,
};

const FIXTURE_PATH: &str = "tests/fixtures/cis/multi_member_cis_alleles.json";

/// Reference bases fetched either side of a row's span, so a normalized output
/// that shifted still lands inside the window it is compared in.
const WINDOW_FLANK: u64 = 200;

/// Widest window worth fetching. A row spanning more than this is a structural
/// call whose bases are not the interesting part; fetching megabases to compare
/// them would dominate the run.
const MAX_WINDOW: u64 = 100_000;

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct Row {
    input: String,
    /// The harvester's own member count, taken from the parsed allele. See
    /// [`the_harvested_member_census_is_unchanged`], which re-derives it from
    /// the string alone and pins that the two agree.
    members: usize,
}

#[derive(Deserialize)]
struct Fixture {
    rows_scanned: usize,
    rows: Vec<Row>,
}

fn fixture() -> &'static Fixture {
    static FIXTURE: OnceLock<Fixture> = OnceLock::new();
    FIXTURE.get_or_init(|| {
        let text = fs::read_to_string(FIXTURE_PATH)
            .unwrap_or_else(|e| panic!("failed to read {FIXTURE_PATH}: {e}"));
        serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("failed to parse {FIXTURE_PATH}: {e}"))
    })
}

// ---------------------------------------------------------------------------
// Syntax: members and the gaps between them
// ---------------------------------------------------------------------------

/// Split the contents of an allele's outer brackets on `;` **at depth zero**.
///
/// A naive `split(';')` over-counts, because an inserted-range payload carries
/// its own brackets and its own separator (`g.[a_bins[SEQ;c_d];e_finsAT]`).
///
/// This is deliberately a *second, independent* derivation of a figure the
/// harvester already records: the harvester gets its count from `parse_hgvs`,
/// and this one gets it from the string. Pinning that they agree
/// ([`the_harvested_member_census_is_unchanged`]) is what would catch the
/// fixture being regenerated by a selection rule that had drifted away from
/// what the parser sees.
fn split_members(inner: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut depth = 0i32;
    let mut start = 0usize;
    for (index, byte) in inner.bytes().enumerate() {
        match byte {
            b'[' | b'(' => depth += 1,
            b']' | b')' => depth -= 1,
            b';' if depth == 0 => {
                out.push(&inner[start..index]);
                start = index + 1;
            }
            _ => {}
        }
    }
    out.push(&inner[start..]);
    out
}

/// The `;`-separated members inside a row's outer brackets, bracket-aware.
fn members_of(input: &str) -> Vec<&str> {
    let (Some(open), Some(close)) = (input.find('['), input.rfind(']')) else {
        return Vec::new();
    };
    if close <= open {
        return Vec::new();
    }
    split_members(&input[open + 1..close])
}

/// The 1-based `(start, end)` a member names, when that is a pair of plain
/// integers.
///
/// `None` when the member carries an intronic offset (`453+625`), a UTR anchor
/// (`*17`, `-30`) or a non-numeric position. Deliberately so: the *distance*
/// between two such members is not a number that can be read off the string —
/// `c.100+50` and `c.101-50` may be thousands of bases apart or adjacent,
/// depending on the intron — and a census that guessed would be worse than one
/// that abstains and says how often it did.
fn plain_span(member: &str) -> Option<(u64, u64)> {
    // A member may carry its own coordinate prefix in a mixed allele
    // (`[c.1del;c.5del]`).
    let body = match member.as_bytes() {
        [_, b'.', ..] => &member[2..],
        _ => member,
    };
    let (start, rest) = leading_number(body)?;
    let end = match rest.strip_prefix('_') {
        Some(tail) => leading_number(tail)?.0,
        None => start,
    };
    Some((start, end))
}

/// A leading run of digits, rejected when it is followed by an offset marker.
fn leading_number(text: &str) -> Option<(u64, &str)> {
    let digits = text.bytes().take_while(u8::is_ascii_digit).count();
    if digits == 0 {
        return None;
    }
    let rest = &text[digits..];
    if rest.starts_with('+') || rest.starts_with('-') {
        return None;
    }
    text[..digits].parse().ok().map(|n| (n, rest))
}

/// Unchanged bases between two consecutive members, as a bucket label.
///
/// The buckets are what the generated corpus in `cis_confluence_axis` is a
/// deliberate complement to: it enumerates separations 0, 1, 2, 3, 5 and 8,
/// which is where a partitioner has a decision to make.
fn separation_bucket(previous_end: u64, next_start: u64) -> &'static str {
    if next_start <= previous_end {
        return "overlapping or unordered";
    }
    match next_start - previous_end - 1 {
        0 => "0 (adjacent)",
        1 => "1",
        2 => "2",
        3 => "3",
        4..=8 => "4-8",
        9..=99 => "9-99",
        100..=999 => "100-999",
        _ => "1000+",
    }
}

/// The gap census over every consecutive member pair in the fixture.
fn separation_census() -> BTreeMap<&'static str, usize> {
    let mut census = BTreeMap::new();
    for row in &fixture().rows {
        let members = members_of(&row.input);
        for pair in members.windows(2) {
            let bucket = match (plain_span(pair[0]), plain_span(pair[1])) {
                (Some((_, previous_end)), Some((next_start, _))) => {
                    separation_bucket(previous_end, next_start)
                }
                _ => "not readable from the string",
            };
            *census.entry(bucket).or_insert(0) += 1;
        }
    }
    census
}

// ---------------------------------------------------------------------------
// Always-on tier
// ---------------------------------------------------------------------------

/// Every harvested row is a multi-member cis allele the parser accepts.
///
/// This is an assertion of zero, not a pinned split, because the harvester
/// *decides* with `parse_hgvs`: a row is written to the fixture only if it
/// parses as an `AllelePhase::Cis` allele with more than one member. So the
/// fixture's 592 rows are 592 pieces of evidence about the partitioner, with
/// nothing to discount.
///
/// It reached that state by dropping 58 rows a purely syntactic selection had
/// admitted, in two groups:
///
/// * **46 malformed corpus strings** ferro rejects by design — substitutions run
///   together with no separator (`c.[1327G>T;1727G>C2002C>T]`), a member
///   repeating the coordinate prefix (`c.[652C>T;c.940A>G]`), methylation edits
///   (`gom`/`lom`). They are real ClinVar rows and they are worth having as
///   *parser* evidence, but they never reach `canonicalize_from_sequence`, so
///   they were never evidence about this code path.
/// * **12 rows that are not alleles at all** — a single variant whose
///   inserted-range payload happens to carry a `;`
///   (`g.80114186_80114187ins[80114172_80114186;NC_000020.11:g.2823027_2826302;AAA]`),
///   which a `find('[')..rfind(']')` scan reads as a member list.
///
/// A failure here is therefore one of two things, and the message says which:
/// the fixture is stale against a parser that has changed, or it was
/// regenerated by a selection rule that no longer matches the parser.
/// Re-harvest (`cargo run --features dev --example harvest_multi_member_cis`)
/// and review what moved.
#[test]
fn the_harvested_rows_parse_as_multi_member_alleles() {
    let mut accepted = 0usize;
    let mut wrong_shape = Vec::new();
    for row in &fixture().rows {
        match parse_hgvs(&row.input) {
            Ok(HgvsVariant::Allele(allele)) if allele.variants.len() > 1 => {
                accepted += 1;
                assert_eq!(
                    allele.variants.len(),
                    row.members,
                    "{}: recorded {} members, parses as {}",
                    row.input,
                    row.members,
                    allele.variants.len()
                );
            }
            Ok(_) => wrong_shape.push(format!(
                "{}: parses, but not as a multi-member allele",
                row.input
            )),
            Err(e) => wrong_shape.push(format!("{}: {e}", row.input)),
        }
    }
    println!("harvested rows: {accepted} multi-member alleles");
    assert!(
        wrong_shape.is_empty(),
        "{} harvested rows are not multi-member alleles. The harvester selects \
         on `parse_hgvs`, so this means the fixture is stale against the parser \
         or was regenerated by a different rule:\n{}",
        wrong_shape.len(),
        wrong_shape.join("\n")
    );
    assert_eq!(accepted, 592, "harvested multi-member cis alleles");
}

/// The harvest's own census, pinned. Regenerating the fixture against different
/// corpora moves these, and that is a review-visible event rather than a silent
/// one.
#[test]
fn the_harvested_member_census_is_unchanged() {
    let fixture = fixture();
    assert_eq!(fixture.rows_scanned, 9_949_738, "corpus rows scanned");
    assert_eq!(
        fixture.rows.len(),
        592,
        "multi-member cis alleles harvested"
    );

    let mut census: BTreeMap<usize, usize> = BTreeMap::new();
    for row in &fixture.rows {
        *census.entry(row.members).or_insert(0) += 1;
    }
    assert_eq!(
        census,
        BTreeMap::from([(2, 561), (3, 22), (4, 6), (6, 3)]),
        "members per harvested allele, as the parser counted them"
    );

    // The same census re-derived from the strings alone, by a depth-aware split
    // that owes nothing to the parser. The two agree on every row — including
    // `LRG_501:g.[...ins[SEQ;a_b]...]`, whose payload `;` a naive `split(';')`
    // counts as a fourth member. That agreement is the point: it is what would
    // fail if the fixture were ever regenerated by a selection rule that had
    // drifted from what `parse_hgvs` sees.
    let mut bracket_aware: BTreeMap<usize, usize> = BTreeMap::new();
    for row in &fixture.rows {
        *bracket_aware
            .entry(members_of(&row.input).len())
            .or_insert(0) += 1;
    }
    assert_eq!(
        bracket_aware, census,
        "a depth-aware recount from the string disagrees with the harvester's \
         parsed member count"
    );
}

/// The distribution this whole issue rests on: in observed data, two changes in
/// one allele are almost never close enough to share a block.
///
/// If this census ever shifts towards the small buckets, the argument for the
/// generated corpus weakens and the argument for testing against real data
/// strengthens — so it is worth failing on.
#[test]
fn the_separation_census_is_unchanged() {
    let census = separation_census();
    println!("inter-member separations: {census:?}");
    assert_eq!(
        census,
        BTreeMap::from([
            ("0 (adjacent)", 24),
            ("1", 14),
            ("2", 17),
            ("3", 13),
            ("4-8", 38),
            ("9-99", 107),
            ("100-999", 163),
            ("1000+", 98),
            ("not readable from the string", 83),
            ("overlapping or unordered", 81),
        ]),
        "the inter-member separation distribution moved"
    );

    // The whole argument for a generated corpus, in one line: of 638 member
    // pairs, **106** are within eight bases of each other — the range where a
    // partitioner has a decision to make — and 261 are a hundred or more bases
    // apart. `cis_confluence_axis` generates 11 280 classes concentrated in
    // exactly that first bucket, which no amount of observed data supplies.
    let close: usize = ["0 (adjacent)", "1", "2", "3", "4-8"]
        .iter()
        .map(|bucket| census[bucket])
        .sum();
    assert_eq!(close, 106, "member pairs within eight bases of each other");
    assert_eq!(census.values().sum::<usize>(), 638, "member pairs censused");
}

// ---------------------------------------------------------------------------
// Manifest-gated tier
// ---------------------------------------------------------------------------

fn manifest_path() -> Option<PathBuf> {
    // Same convention as `biocommons_normalize_tests`: `FERRO_MANIFEST` is
    // authoritative when set, with a well-known fallback.
    if let Ok(path) = std::env::var("FERRO_MANIFEST") {
        let path = PathBuf::from(path);
        return path.exists().then_some(path);
    }
    let fallback = Path::new("benchmark-output/manifest.json");
    fallback.exists().then(|| fallback.to_path_buf())
}

fn provider() -> Option<Arc<MultiFastaProvider>> {
    static PROVIDER: OnceLock<Option<Arc<MultiFastaProvider>>> = OnceLock::new();
    PROVIDER
        .get_or_init(|| {
            // A missing manifest is the legitimate skip. A manifest that is
            // present but will not load is a misconfiguration, and reporting it
            // as a no-op skip would hide it.
            let path = manifest_path()?;
            Some(Arc::new(
                MultiFastaProvider::from_manifest(&path)
                    .unwrap_or_else(|e| panic!("from_manifest({}) failed: {e}", path.display())),
            ))
        })
        .clone()
}

/// What the gated run found. Pinned as a baseline; see the module docs.
#[derive(Debug, Default, PartialEq, Eq)]
struct AxisCensus {
    rows: usize,
    /// Rows normalization declined or panicked on.
    declined: usize,
    /// Rows whose output is not its own normalized form.
    not_idempotent: usize,
    /// Rows whose reference window could not be assembled — a member with no
    /// SPDI triple, members on different sequences, or a span wider than
    /// [`MAX_WINDOW`]. Counted so "0 sequence changes" cannot quietly mean
    /// "nothing was checked".
    unwindowed: usize,
    /// Rows whose normalized output denotes a different sequence than the input.
    sequence_changed: usize,
    /// Rows whose spanning-`delins` respelling could be built at all.
    respellable: usize,
    /// … of those, the ones that normalize to the same string as the row.
    respelling_converged: usize,
}

/// A description's SPDI triples, all on one sequence, or `None`.
fn triples_of<P: ReferenceProvider + ?Sized>(
    provider: &P,
    descriptor: &str,
) -> Option<Vec<(String, u64, String, String)>> {
    let members: Vec<HgvsVariant> = match parse_hgvs(descriptor).ok()? {
        HgvsVariant::Allele(allele) => allele.variants.clone(),
        single => vec![single],
    };
    let mut triples = Vec::with_capacity(members.len());
    for member in &members {
        let triple = hgvs_to_spdi(member, provider).ok()?;
        triples.push((
            triple.sequence.clone(),
            triple.position,
            triple.deletion.clone(),
            triple.insertion.clone(),
        ));
    }
    let first = triples.first()?.0.clone();
    triples.iter().all(|t| t.0 == first).then_some(triples)
}

/// Apply triples inside a fetched window, the same 3'→5' walk as
/// `common::cis_apply_oracle::apply_reason` but with window-relative offsets.
fn apply_in_window(
    window: &str,
    window_start: u64,
    triples: &[(String, u64, String, String)],
) -> Option<String> {
    let mut ordered: Vec<&(String, u64, String, String)> = triples.iter().collect();
    ordered.sort_by_key(|t| (std::cmp::Reverse(t.1), std::cmp::Reverse(t.2.len())));
    let bytes = window.as_bytes();
    let mut edited = bytes.to_vec();
    let mut claimed = window.len();
    let mut insertion_at: Option<usize> = None;
    for (_, position, deletion, insertion) in ordered {
        let start = usize::try_from(position.checked_sub(window_start)?).ok()?;
        let end = start.checked_add(deletion.len())?;
        if end > window.len() || end > claimed {
            return None;
        }
        if deletion.is_empty() && insertion_at == Some(start) {
            return None;
        }
        if !bytes[start..end].eq_ignore_ascii_case(deletion.as_bytes()) {
            return None;
        }
        edited.splice(start..end, insertion.bytes());
        if deletion.is_empty() {
            insertion_at = Some(start);
        }
        claimed = start;
    }
    String::from_utf8(edited).ok()
}

/// The window a set of triples needs, plus the bases in it.
fn window_for<P: ReferenceProvider + ?Sized>(
    provider: &P,
    triples: &[(String, u64, String, String)],
) -> Option<(u64, String)> {
    let sequence = &triples.first()?.0;
    let lo = triples.iter().map(|t| t.1).min()?;
    let hi = triples.iter().map(|t| t.1 + t.2.len() as u64).max()?;
    if hi.saturating_sub(lo) > MAX_WINDOW {
        return None;
    }
    let start = lo.saturating_sub(WINDOW_FLANK);
    let end = hi + WINDOW_FLANK;
    let bases = provider.get_sequence(sequence, start, end).ok()?;
    // A window truncated at the end of the sequence still starts where we asked.
    Some((start, bases))
}

/// The spanning-`delins` respelling of a row, when its members name plain
/// positions on one axis.
///
/// Deliberately narrow. The union of two members carrying intronic offsets is
/// not a contiguous span in the coordinate system they are written in, so there
/// is no honest single-`delins` spelling of it; rows like that are counted as
/// not respellable rather than respelled wrongly.
fn spanning_respelling(
    input: &str,
    window: &str,
    window_start: u64,
    triples: &[(String, u64, String, String)],
) -> Option<String> {
    let (accession, axis) = input.split_once(':')?;
    let axis_prefix = axis.get(..2)?;
    if !axis_prefix.ends_with('.') {
        return None;
    }
    let members = members_of(input);
    if members.len() < 2 {
        return None;
    }
    // Every member must name plain positions, and none may be a pure insertion:
    // an insertion's written positions straddle its junction, so the union of a
    // set including one does not line up with the union of the SPDI spans.
    let mut low = u64::MAX;
    let mut high = 0u64;
    for member in &members {
        let (start, end) = plain_span(member)?;
        if member.contains("ins") && !member.contains("delins") {
            return None;
        }
        low = low.min(start);
        high = high.max(end);
    }
    let spdi_low = triples.iter().map(|t| t.1).min()?;
    let spdi_high = triples.iter().map(|t| t.1 + t.2.len() as u64).max()?;
    // The written span and the SPDI span must describe the same number of
    // bases, or the two coordinate frames do not correspond and the respelling
    // would be nonsense.
    if spdi_high.checked_sub(spdi_low)? != high.checked_sub(low)? + 1 {
        return None;
    }

    let applied = apply_in_window(window, window_start, triples)?;
    let prefix = usize::try_from(spdi_low - window_start).ok()?;
    let suffix = window
        .len()
        .checked_sub(usize::try_from(spdi_high - window_start).ok()?)?;
    if applied.len() < prefix + suffix {
        return None;
    }
    let alt = &applied[prefix..applied.len() - suffix];
    if alt.is_empty() {
        return Some(format!("{accession}:{axis_prefix}{low}_{high}del"));
    }
    Some(format!("{accession}:{axis_prefix}{low}_{high}delins{alt}"))
}

fn measure_axis(provider: &Arc<MultiFastaProvider>) -> AxisCensus {
    let normalizer = Normalizer::with_config(provider.clone(), NormalizeConfig::default());
    let mut census = AxisCensus::default();

    for row in &fixture().rows {
        census.rows += 1;
        let Ok(variant) = parse_hgvs(&row.input) else {
            census.declined += 1;
            continue;
        };
        let normalized = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            normalizer.normalize(&variant)
        }));
        let Ok(Ok(output)) = normalized else {
            census.declined += 1;
            continue;
        };
        let output = output.to_string();

        // Idempotence: the output must be its own normalized form.
        let again = parse_hgvs(&output).ok().and_then(|v| {
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| normalizer.normalize(&v)))
                .ok()
                .and_then(|r| r.ok())
                .map(|v| v.to_string())
        });
        if again.as_deref() != Some(output.as_str()) {
            census.not_idempotent += 1;
        }

        // Sequence preservation, over a window both descriptions fit in.
        let (Some(input_triples), Some(output_triples)) = (
            triples_of(provider.as_ref(), &row.input),
            triples_of(provider.as_ref(), &output),
        ) else {
            census.unwindowed += 1;
            continue;
        };
        let combined: Vec<_> = input_triples
            .iter()
            .chain(output_triples.iter())
            .cloned()
            .collect();
        let Some((window_start, window)) = window_for(provider.as_ref(), &combined) else {
            census.unwindowed += 1;
            continue;
        };
        let from_input = apply_in_window(&window, window_start, &input_triples);
        let from_output = apply_in_window(&window, window_start, &output_triples);
        match (from_input, from_output) {
            (Some(before), Some(after)) if before == after => {}
            (None, _) => census.unwindowed += 1,
            _ => census.sequence_changed += 1,
        }

        // The spanning respelling, where one exists.
        let Some(respelling) =
            spanning_respelling(&row.input, &window, window_start, &input_triples)
        else {
            continue;
        };
        census.respellable += 1;
        let respelled = parse_hgvs(&respelling).ok().and_then(|v| {
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| normalizer.normalize(&v)))
                .ok()
                .and_then(|r| r.ok())
                .map(|v| v.to_string())
        });
        if respelled.as_deref() == Some(output.as_str()) {
            census.respelling_converged += 1;
        }
    }

    census
}

/// The pinned gated census, measured against a prepared reference.
///
/// How to read it. **0 declined**: the harvester selects on `parse_hgvs`, so
/// every row parses, and the normalizer declines none of them. **96 unwindowed**
/// are rows whose members do not all resolve to SPDI triples on one sequence, or
/// whose span is wider than [`MAX_WINDOW`]; they are counted rather than skipped
/// so `sequence_changed: 0` cannot quietly mean "nothing was checked".
///
/// The two numbers worth arguing about are the last pair: of **461** rows whose
/// spanning-`delins` respelling can be built at all, **376 (82%)** normalize to
/// the same string as the row itself, and 85 do not. That 82% is the real-data
/// counterpart to the 59% `cis_confluence_axis` measures over designed alleles,
/// and the gap between them is the point of this issue: real rows are easy
/// because their members are far apart (see
/// [`the_separation_census_is_unchanged`]), so they do not exercise the
/// partitioner that the designed corpus does.
///
/// `respelling_converged` must only ever go up; `not_idempotent` and
/// `sequence_changed` are asserted at zero on their own before the comparison,
/// so a regression there names itself rather than surfacing as a moved tuple.
///
/// # LOWERED BY TWO, 376 -> 374, and the direction is deliberate
///
/// This is the one place the ratchet has been turned back, so it needs its
/// reason recorded next to the number rather than in a commit message.
///
/// The typing-widening repair in this change stops a rendered member covering
/// territory its asserted span did not claim — the shape where `g.[2_3dup;5_6insA]`
/// came out as `g.[1_9T[11];5_6insA]`, a tract containing the sibling's `5|6`
/// junction. Two of these 461 rows reached their converged form *through* such a
/// widening, so refusing it costs their convergence.
///
/// That trade is what `adjudication-precedence-order` ranks, and it is not close:
/// an allele whose members claim the same territory **denotes no single
/// sequence**, so emitting one is a rank-(1) validity failure, while convergence
/// is rank (2). Rank (1) is absolute and never traded, so two lost convergences
/// is the correct price and not a regression to be argued down. It is also *not*
/// a `PRECEDENCE_ESCALATIONS` entry: an escalation is confluence overriding the
/// recommended form, and here validity simply outranks confluence, which is the
/// ordinary case the ladder describes.
///
/// What would make this a real regression, and is separately asserted above:
/// `sequence_changed` rising. The rejected alternative repair — re-spelling the
/// growth at the *tract's* 3' junction rather than the asserted member's — turned
/// `g.[2_3dup;5_6insA]` into `g.[5_6insA;8_9dup]`, which is disjoint,
/// warning-free, re-parses, and denotes a **different sequence**. It would have
/// raised this ratchet while corrupting data. Convergence going up is therefore
/// not on its own evidence of an improvement here.
const AXIS_CENSUS: AxisCensus = AxisCensus {
    rows: 592,
    declined: 0,
    not_idempotent: 0,
    unwindowed: 96,
    sequence_changed: 0,
    respellable: 461,
    respelling_converged: 374,
};

#[test]
fn axis_normalized() {
    let Some(provider) = provider() else {
        println!(
            "multi-member-cis: skipping — no reference manifest at FERRO_MANIFEST or \
             benchmark-output/manifest.json"
        );
        return;
    };
    let census = measure_axis(&provider);
    println!("multi-member-cis axis: {census:?}");
    assert_eq!(
        census.not_idempotent, 0,
        "{} rows normalize to something that is not its own normalized form",
        census.not_idempotent
    );
    assert_eq!(
        census.sequence_changed, 0,
        "{} rows normalize to a description of a different sequence",
        census.sequence_changed
    );
    assert_eq!(
        census, AXIS_CENSUS,
        "the multi-member cis axis census moved; `respelling_converged` must only ever go up"
    );
}

/// The nested-payload case the harvester's prefilter cannot see.
#[test]
fn members_are_split_outside_nested_payloads() {
    assert_eq!(
        members_of("T:g.[1del;5_6insAA]"),
        vec!["1del", "5_6insAA"],
        "a plain two-member allele"
    );
    assert_eq!(
        members_of("T:g.[1_2ins[AC;10_20];30_31insAT]"),
        vec!["1_2ins[AC;10_20]", "30_31insAT"],
        "the `;` inside an inserted-range payload is not a member separator"
    );
}

/// The census abstains rather than guessing whenever a position is not a
/// plain integer, which is the whole reason it is trustworthy.
#[test]
fn only_plain_positions_yield_a_span() {
    assert_eq!(plain_span("2504G>T"), Some((2504, 2504)));
    assert_eq!(plain_span("100_105del"), Some((100, 105)));
    assert_eq!(plain_span("c.100_105del"), Some((100, 105)));
    assert_eq!(plain_span("453+625_545+921delinsTG"), None);
    assert_eq!(plain_span("100-5del"), None);
    assert_eq!(plain_span("*17del"), None);
    assert_eq!(plain_span("(100_200)del"), None);
}

#[test]
fn separations_bucket_by_distance() {
    assert_eq!(separation_bucket(10, 11), "0 (adjacent)");
    assert_eq!(separation_bucket(10, 12), "1");
    assert_eq!(separation_bucket(10, 20), "9-99");
    assert_eq!(separation_bucket(10, 10), "overlapping or unordered");
    assert_eq!(separation_bucket(10, 2000), "1000+");
}
