//! Named regression tests promoted out of the exhaustive spec corpus.
//!
//! # Why these exist separately from the corpus
//!
//! **A corpus row can silently stop being generated.** That is this repository's
//! recorded blindness class, three times over: #1456 (every family paired members
//! on disjoint territory, so no conflicting allele existed and `0 of 18,432` was
//! reported three times as evidence), #1460 (20-mer cores, so nothing reached
//! `MAX_SPLIT_BLOCK` and a length-gated change was structurally invisible), #1478
//! (`Exon::with_genomic(1, 1, tx_len, …)` builds ONE exon with `CDS_START = 1`, so
//! no row could cross a junction or sit in the 5'UTR). Each was invisible to the
//! one before it.
//!
//! A named committed test cannot be un-generated by a later edit to the
//! generator. So: **the corpus for breadth, these for anything that ever went
//! red.**
//!
//! # These pin DEFECTS, not answers
//!
//! Every expectation below is what ferro produces on `main` at 35de96c8, and in
//! most cases it is **wrong**. Each test states the question, the answer the cited
//! clause gives, and what ferro does instead — the `KNOWN_DIVERGENT_INPUTS`
//! pattern, which exists so a deviation stays visible rather than rotting into an
//! assumption. When one is fixed, the assertion moves to the correct value in the
//! same commit and the comment says so.
//!
//! Not fixed here on purpose: a PR that both built this instrument and changed the
//! normalizer would have no baseline to measure the change against.

use ferro_hgvs::conformance::spec_corpus::{
    corpus_cores, denotation_of, Denotation, Frame, RefShape, DENSE_CORE_LEN,
};
use ferro_hgvs::reference::transcript::Strand;
use ferro_hgvs::{parse_hgvs, NormalizeConfig, Normalizer, ShuffleDirection};

/// The `AT`-alphabet core the corpus draws first. Chosen because a two-letter
/// alphabet makes long runs, which is where junction-crossing shifts live.
fn at_core() -> String {
    corpus_cores(1, DENSE_CORE_LEN).remove(0)
}

/// The `ACGT`-alphabet core, for rows whose defect needs a non-degenerate
/// neighbourhood.
fn acgt_core() -> String {
    corpus_cores(1, DENSE_CORE_LEN).remove(1)
}

/// Normalize `input` against `frame`, in the given direction.
fn normalize(frame: &Frame, input: &str, direction: ShuffleDirection) -> String {
    let variant = parse_hgvs(input).unwrap_or_else(|e| panic!("{input} must parse: {e}"));
    let normalizer = Normalizer::with_config(
        frame.provider().clone(),
        NormalizeConfig::default().with_direction(direction),
    );
    normalizer
        .normalize(&variant)
        .unwrap_or_else(|e| panic!("{input} must normalize: {e}"))
        .to_string()
}

/// Normalize in the default (3') direction.
fn normalize_3prime(frame: &Frame, input: &str) -> String {
    normalize(frame, input, ShuffleDirection::ThreePrime)
}

// ---------------------------------------------------------------------------
// The 3' shift crosses an exon junction on a MINUS-strand transcript
// ---------------------------------------------------------------------------

/// **Question.** May the 3' shift move a deletion out of an exon and into the
/// following intron?
///
/// **Yes — the shift is legal. It is the ACCESSION that is not.** This doc
/// comment previously said "the clauses say no, twice" and cited `general.md:44`
/// as forbidding the shift. That was backwards, and it mattered: it named a
/// target that would implement an exception the spec explicitly withholds.
///
/// `general.md:44` defers to `background/numbering.md`, which scopes its
/// exception twice — `:23` applies it to **exon/exon** junctions "where shifting
/// the variant 3' would place it in the **next exon**", and `:26` states that it
/// "**does not apply** to a deletion/duplication around **exon/intron and
/// intron/exon** junctions". This row is exactly the exon→intron case `:26`
/// excludes, and ferro already blocks the exon→exon case the exception covers.
///
/// What IS violated is `checklist.md:20`: "NM reference sequences cover mature
/// transcripts and **do not contain** intron and gene flanking sequences, and can
/// only be used to describe variants in introns using a `c.` prefix when a
/// genomic reference sequence is given". So the output names a position its own
/// accession cannot express. Converging on the clamped `c.20del` would revert
/// #670; the live candidates are re-parenting onto a genomic wrapper, or refusal.
///
/// **The strand is a confound, not a finding.** The plus/minus difference below
/// is real but is a property of the fixture: the provider writes a literal
/// `GATTACA` intron and reverse-complements only the exon blocks, so against an
/// `AT` core `G` never continues a run and `AA` always does. Hold the
/// transcript-direction intron fixed and both strands agree — see
/// `defect_371_transcript_exit.rs`, whose `junction_provider` takes the intron as
/// a parameter for precisely this reason.
///
/// This is the largest single class the corpus found — **371 outputs on the 3'
/// direction and 0 on the 5'** — and it is structurally invisible to a
/// single-exon fixture, which is #1478 exactly. The 0 at 5' is a claim about the
/// code, not the corpus: all three copies of the #670 gate are guarded on
/// `ThreePrime` with no 5' mirror.
#[test]
fn a_minus_strand_junction_shift_leaves_the_transcript() {
    let core = at_core();
    let plus = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    let minus = Frame::build(RefShape::CodingMultiExon(Strand::Minus), &core);

    // The contrast, NOT the target: on the plus strand the shift stops inside
    // the exon. That is a property of this fixture's intron, not a clamp the
    // minus strand is failing to apply — see the doc comment.
    assert_eq!(
        normalize_3prime(&plus, "NM_TEST.1:c.17del"),
        "NM_TEST.1:c.20del",
        "the plus-strand contrast: same design, intron that does not continue the run"
    );

    // The defect: on the minus strand it walks two bases into the intron.
    assert_eq!(
        normalize_3prime(&minus, "NM_TEST.1:c.17del"),
        "NM_TEST.1:c.20+2del",
        "PINNED DEFECT — the SHIFT is legal (numbering.md:26 withholds general.md:44's \
         exception from exon/intron junctions); what is invalid is the ACCESSION, since \
         checklist.md:20 forbids a bare NM_ from naming an intronic position. The target is \
         therefore a genomic wrapper or a refusal — NOT c.20del, which would implement an \
         exception the spec explicitly excludes and would revert #670."
    );
}

/// **Question.** What happens when *two* members of one allele both shift past
/// the same junction?
///
/// **They land on the same base.** `c.[20del;17del]` becomes
/// `c.[20+2del;20+2del]` — two identical members, which denotes no sequence at
/// all: the second deletion has nothing left to delete. `general.md:58`'s
/// neighbourhood is the closest clause ("descriptions removing part of a
/// reference sequence and replacing it with part of the same sequence are not
/// allowed"), but the plainer statement is that a description must denote one
/// sequence, and this one denotes none.
///
/// Kept separate from the single-member case because it is a *different* failure:
/// the single-member output is expressible-but-prohibited, this one is
/// self-contradictory, and only a multi-member allele can produce it.
#[test]
fn two_members_shifting_past_one_junction_collide_into_identical_members() {
    let core = at_core();
    let minus = Frame::build(RefShape::CodingMultiExon(Strand::Minus), &core);

    let output = normalize_3prime(&minus, "NM_TEST.1:c.[20del;17del]");
    assert_eq!(
        output, "NM_TEST.1:c.[20+2del;20+2del]",
        "PINNED DEFECT — two identical members denote no sequence. Correct output: \
         NM_TEST.1:c.19_20del, which is what the plus-strand control gives."
    );

    // The plus-strand control, so the strand-specificity is pinned too and a
    // future fix cannot quietly break the side that works.
    let plus = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    assert_eq!(
        normalize_3prime(&plus, "NM_TEST.1:c.[20del;17del]"),
        "NM_TEST.1:c.19_20del"
    );
}

// ---------------------------------------------------------------------------
// Conflicting alleles are normalized instead of refused (#1456's shape)
// ---------------------------------------------------------------------------

/// **Question.** Must a description whose members claim the same reference
/// territory be refused?
///
/// **Yes — it denotes no sequence.** `general.md:58`: "descriptions removing part
/// of a reference sequence and replacing it with part of the same sequence are not
/// allowed (e.g., `NM_004006.2:c.[762_768del;767_774dup]`)". Ferro already
/// enforces exactly that spelling — a `del` plus an overlapping `dup` is rejected
/// at parse with "Self-cancelling allele" — but the check is keyed on that pair of
/// edit types, so a `del` plus an overlapping `del` sails through.
///
/// Three geometries, all accepted, **72 rows in total**. Every one of them was
/// structurally impossible to generate before #1456: the designed corpus paired
/// members on disjoint territory only, and reported `0 of 18,432` three times.
#[test]
fn conflicting_member_geometries_are_normalized_instead_of_refused() {
    let core = at_core();
    let frame = Frame::build(RefShape::CodingSingleExon, &core);
    let served = frame.served();

    for (geometry, input) in [
        // One member's footprint strictly inside another's.
        ("nested", "NM_TEST.1:c.[9_12del;10_11del]"),
        // Footprints that partially intersect.
        ("overlapping", "NM_TEST.1:c.[9_12del;11_14del]"),
        // Two pure insertions at one interbase, which have no order.
        ("coincident insertions", "NM_TEST.1:c.[8_9insAC;8_9insCC]"),
    ] {
        // First, the premise: the input really does denote no sequence. Without
        // this the test would be asserting a preference rather than a defect.
        assert_eq!(
            denotation_of(frame.provider(), served, input),
            Denotation::NoSequence,
            "{geometry}: {input} must denote no sequence for this test to mean anything"
        );

        // The defect: ferro accepts it and hands back a description.
        let output = normalize_3prime(&frame, input);
        assert_eq!(
            output, input,
            "PINNED DEFECT ({geometry}) — general.md:58 makes a description that claims one \
             territory twice invalid, and ferro already rejects the del+dup spelling the clause \
             names. Correct behaviour: refuse."
        );
    }
}

// ---------------------------------------------------------------------------
// Absolute prohibitions accepted, and re-emitted
// ---------------------------------------------------------------------------

/// **Question.** Are the shapes the checklist calls "not allowed" rejected?
///
/// **Three are not**, and each is accepted both standalone and inside an allele,
/// then emitted again unchanged — so the prohibition is enforced on neither the
/// input nor the output side.
///
/// The clauses, verbatim:
///
/// - `checklist.md:33` — "Describing a variant as `c.5439_5430ins6` is not
///   allowed, the inserted sequence (for `ins6`, e.g., `TGCCAT`) should be
///   specified." Ferro *does* reject `ins6` when the two anchors are not adjacent
///   (per `DNA/insertion.md:15`), which is a different check that happens to
///   catch the spec's own example; with adjacent anchors nothing fires.
/// - `checklist.md:16` — a genomic reference "can not have nucleotides with
///   additions like a `+`, `-`, or `*`".
/// - `checklist.md:45` — "Not correct is `c.12-14del`, this describes a deletion
///   of nucleotide -14 in the intron directly 5' of nucleotide `c.12`". On a
///   genomic axis there is no intron to read it into, so the shape has no legal
///   reading at all.
#[test]
fn absolute_prohibitions_are_accepted_and_re_emitted() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    let genomic = Frame::build(RefShape::Genomic, &core);

    // `ins6`: an insertion that states a LENGTH instead of a sequence.
    assert_eq!(
        normalize_3prime(&coding, "NM_TEST.1:c.10_11ins6"),
        "NM_TEST.1:c.10_11ins6",
        "PINNED DEFECT — checklist.md:33 says an insertion sized by a number 'is not allowed, \
         the inserted sequence … should be specified'. Correct behaviour: refuse."
    );

    // A `+` offset on a genomic axis, which has no introns to hang one off.
    assert_eq!(
        normalize_3prime(&genomic, "NC_TEST.1:g.266+2del"),
        "NC_TEST.1:g.266+2del",
        "PINNED DEFECT — checklist.md:16 says a `g.` reference 'can not have nucleotides with \
         additions like a `+`, `-`, or `*`'. Correct behaviour: refuse."
    );

    // A hyphen where the range separator belongs.
    assert_eq!(
        normalize_3prime(&genomic, "NC_TEST.1:g.266-268del"),
        "NC_TEST.1:g.266-268del",
        "PINNED DEFECT — checklist.md:45 calls the hyphen form 'Not correct', and on a genomic \
         axis it has no intronic reading either. Correct behaviour: refuse."
    );
}

/// **Question.** Does a prohibited member become *less* visible when it sits
/// inside an allele?
///
/// **This one does, and that is the more interesting half.** The three shapes
/// above are accepted standalone, so an allele containing one is unsurprising —
/// but it matters that the allele form is checked, because a hygiene check that
/// runs once per description rather than once per member is a failure mode with
/// its own signature, and the corpus generates both forms of every prohibition
/// precisely to tell them apart.
///
/// Note the reordering: ferro sorts members by position, so the offending member
/// moves. That is the 3' rule doing its job and is not the defect.
#[test]
fn a_prohibited_member_inside_an_allele_is_also_accepted() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    assert_eq!(
        normalize_3prime(&coding, "NM_TEST.1:c.[10_11ins6;9del]"),
        "NM_TEST.1:c.[9del;10_11ins6]",
        "PINNED DEFECT — see `absolute_prohibitions_are_accepted_and_re_emitted`; the allele \
         form is pinned separately so a per-description-only fix is visible as a partial one."
    );
}

/// **Question.** Is `X` a nucleotide?
///
/// **No.** `background/standards.md` lists it in the DNA symbol table and then
/// footnotes it at `:39` — "† used in alignment only" — alongside `-`. So neither
/// is a base a description may state. Ferro rejects `-` (the parser stops at it)
/// and accepts `X`.
///
/// Classified `conditional` rather than `absolute` in the corpus, because the
/// footnote states a scope rather than using prohibitive words. It is pinned as a
/// finding to adjudicate, not asserted as a regression.
#[test]
fn an_alignment_only_x_base_is_accepted_as_a_nucleotide() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    assert_eq!(
        normalize_3prime(&coding, "NM_TEST.1:c.10delinsX"),
        "NM_TEST.1:c.10delinsX",
        "PINNED FINDING — standards.md:39 footnotes `X` as 'used in alignment only'. Whether \
         that is a refusal is an adjudication; what is not in doubt is that `X` is not one of \
         the 15 symbols a description may state."
    );
    // The sibling symbol IS rejected, which is what makes the pair worth pinning
    // together: the two are footnoted identically and treated differently.
    assert!(
        parse_hgvs("NM_TEST.1:c.10delins-").is_err(),
        "`-` is rejected while `X` is accepted, though standards.md:39 footnotes both"
    );
}

/// **Question.** May an intronic position be written against a bare transcript
/// accession?
///
/// **No.** `checklist.md:20`: "NM reference sequences cover mature transcripts and
/// **do not contain** intron and gene flanking sequences, and can only be used to
/// describe variants in introns using a `c.` prefix when a genomic reference
/// sequence is given on which the coding DNA reference sequence is annotated,
/// e.g., `NC_000023.10(NM_004006.2):c.94-2A>G` or `LRG_199t1:c.94-2A>G`."
///
/// Ferro accepts the bare form. This is why the corpus writes its intronic
/// idempotency rows against `NC_SYNTH.1(NM_TEST.1)` and generates the bare form
/// only as a shape that ought to be refused: a bare `NM_…:c.123+65del` is an
/// **invalid input**, not a test case.
#[test]
fn a_bare_transcript_accession_accepts_an_intronic_position() {
    let core = at_core();
    let frame = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.20+2del"),
        "NM_TEST.1:c.20+2del",
        "PINNED FINDING — checklist.md:20 permits an intronic `c.` position only with a genomic \
         wrapper. Correct behaviour: refuse, or demand the NC_(NM_) form."
    );
    // The wrapper form is what the spec asks for, and ferro accepts it too — so
    // the fix is a refusal of the bare form, not support for the wrapper.
    assert!(parse_hgvs("NC_SYNTH.1(NM_TEST.1):c.20+2del").is_ok());
}

// ---------------------------------------------------------------------------
// The CDS/3'UTR boundary
// ---------------------------------------------------------------------------

/// **Question.** Is an insertion at the CDS/3'UTR boundary a fixed point?
///
/// **No.** `c.*1delinsCTT` normalizes to `c.72_*1insCT`, which normalizes again to
/// `c.72delinsCCT`. Idempotency is not a spec clause — it is an invariant of any
/// normalizer, and `FERRO_ASSERT_IDEMPOTENT` exists to police it — so this is
/// pinned as a defect with no citation to make.
///
/// The shape needs a transcript with a real 3'UTR, which a `CDS_START = 1`
/// single-exon fixture cannot have (#1478). It reproduces on both strands.
#[test]
fn an_insertion_at_the_cds_end_is_not_a_fixed_point() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        let once = normalize_3prime(&frame, "NM_TEST.1:c.*1delinsCTT");
        assert_eq!(once, "NM_TEST.1:c.72_*1insCT");
        let twice = normalize_3prime(&frame, &once);
        assert_eq!(
            twice, "NM_TEST.1:c.72delinsCCT",
            "PINNED DEFECT — normalization must be idempotent. `{once}` is not its own fixed \
             point on the {strand:?} strand."
        );
    }
}

/// **Question.** What does a deletion flush against an insertion at the CDS/3'UTR
/// boundary denote, and does ferro preserve it?
///
/// **It does not.** `c.[72del;72_*1insA]` deletes the last CDS base and inserts
/// `A` at the interbase immediately 3' of it, which denotes
/// `…tx[..83] + "A" + tx[84..]` — the same sequence as `c.72delinsA`. Ferro
/// returns `c.[72delinsTA;*2del]`, which denotes different bases: it keeps a base
/// the input deleted and deletes one the input did not touch.
///
/// **Sequence preservation is the one property no representation argument can
/// excuse**, so this is the most serious of the four rows in its class. It is a
/// `CoincidentEndpoint` geometry — two members sharing an endpoint without their
/// footprints intersecting — which is legal, and which the designed corpus could
/// not build before #1456.
///
/// Honest caveat, recorded rather than glossed: the corpus's applier reads a
/// deletion and a flush insertion in one order (longer deletion first, then the
/// zero-width member), and one *could* argue an insertion anchored on a base the
/// same allele deletes is itself ill-defined. If that reading wins, the fix is a
/// refusal rather than a different output — but it cannot be the output ferro
/// gives, which denotes a third sequence that neither reading produces.
#[test]
fn a_deletion_flush_against_an_insertion_at_the_cds_end_changes_the_sequence() {
    let core = at_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        let input = "NM_TEST.1:c.[72del;72_*1insA]";
        let expected = match denotation_of(frame.provider(), frame.served(), input) {
            Denotation::Sequence(sequence) => sequence,
            other => panic!("the input must denote a sequence, got {other:?}"),
        };
        let output = normalize_3prime(&frame, input);
        assert_eq!(
            output, "NM_TEST.1:c.[72delinsTA;*2del]",
            "PINNED DEFECT on the {strand:?} strand"
        );
        assert_ne!(
            denotation_of(frame.provider(), frame.served(), &output),
            Denotation::Sequence(expected),
            "if this now holds, the defect is FIXED — move the assertion above to the \
             sequence-preserving output and re-bless the axis census in the same commit"
        );
    }
}

// ---------------------------------------------------------------------------
// A negative result, pinned because it is worth as much as a defect
// ---------------------------------------------------------------------------

/// **Question.** Does ferro implement rejected proposal SVD-WG010 — a separation
/// floor of two on an axis with no reading frame?
///
/// **No, and this pins that.** `general.md:36-39` announces a "new
/// recommendation" that "two variants separated by less than two nucleotides
/// should be described as a 'delins'". That note is **stale**: it describes
/// SVD-WG010, opened 2021-05-15 and closed **rejected** 2021-07-31
/// (`consultation/SVD-WG010.md:8`, "The proposal has been **rejected**"). The live
/// rule is `general.md:34`'s floor of one, with `:35`'s codon exception — which
/// cannot reach a frameless axis at all, being conditioned on "together affecting
/// one amino acid".
///
/// This is not hypothetical: `coalesce_coding_frame_separation` once applied the
/// floor of two on a frameless axis and emitted SVD-WG010's own worked example.
/// The corpus measures **0 violations over 210 rows carrying the shape**, and the
/// denominator is asserted non-zero — `0 of 0` is what a rebuilt #1456 looks like.
///
/// Recorded per `CLAUDE.md`'s "record what was refuted, not only what was
/// decided": a measurement that killed a plausible belief is worth as much as the
/// ruling, because the belief recurs.
#[test]
fn a_frameless_irreducible_separation_of_one_is_not_merged() {
    let core = acgt_core();
    let genomic = Frame::build(RefShape::Genomic, &core);
    let served = genomic.served();

    // Two substitutions separated by one unchanged base. A substitution cannot
    // shift, so the separation is irreducible by construction — which is the
    // condition that distinguishes rejected SVD-WG010 from the 3' rule closing a
    // gap inside a run.
    let first = genomic.label(genomic.core_offset() + 8);
    let third = genomic.label(genomic.core_offset() + 10);
    let base_at = |offset: usize| &served[genomic.core_offset() + offset..][..1];
    let alt = |base: &str| if base == "A" { "C" } else { "A" };
    let input = format!(
        "NC_TEST.1:g.[{first}{}>{};{third}{}>{}]",
        base_at(8),
        alt(base_at(8)),
        base_at(10),
        alt(base_at(10))
    );

    let output = normalize_3prime(&genomic, &input);
    let parsed = parse_hgvs(&output).expect("the output re-parses");
    let members = match &parsed {
        ferro_hgvs::HgvsVariant::Allele(allele) => allele.variants.len(),
        _ => 1,
    };
    assert!(
        members >= 2,
        "merging {input} into `{output}` would implement REJECTED SVD-WG010; general.md:34 \
         says two variants separated by one or more nucleotides are described individually"
    );
}

// ---------------------------------------------------------------------------
// A flush deletion + insertion pair is normalized per member, and the members
// interfere
// ---------------------------------------------------------------------------

/// Every homopolymer-run start in the corpus's `AT` core, as `(index, run end)`.
///
/// A run is where a lone deletion is ambiguous under the 3'rule, so it is
/// exactly where a sibling insertion can be transposed past. Derived from the
/// served sequence rather than listed, so the cases track the core.
fn homopolymer_run_starts(served: &str) -> Vec<usize> {
    let bytes = served.as_bytes();
    let mut starts = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let mut j = i;
        while j + 1 < bytes.len() && bytes[j + 1] == bytes[i] {
            j += 1;
        }
        if j > i {
            starts.push(i);
        }
        i = j + 1;
    }
    starts
}

/// **Question.** `c.[Ndel;N_N+1insG]` deletes one base and inserts `G` at the
/// interbase immediately 3' of it, which denotes exactly `c.NG>...` — a
/// substitution. Does ferro preserve that sequence wherever the pair is placed?
///
/// **Everywhere but one place.** Sweeping the flush pair across all 23
/// homopolymer runs in the `AT` core — the only positions where the deletion is
/// ambiguous enough to move — 22 collapse to the substitution and one does not:
/// `c.[72del;72_*1insG]`, at the CDS/3'UTR boundary, comes out as
/// `c.[72delinsTG;*2del]`, which denotes the same bases in the wrong ORDER.
///
/// **The run length is not the variable, and neither is the boundary.** Runs of
/// two through seven all pass, including three-base runs at indices 45, 65 and
/// 70; both UTRs pass internally. The one failing row is pinned below rather
/// than excluded, and this test **fails when it starts passing** — that is
/// deliberate, in the `KNOWN_DIVERGENT_INPUTS` tradition: a fixed deviation must
/// not rot in a list unnoticed. When it goes green, delete the pin.
#[test]
fn a_flush_deletion_and_insertion_preserves_the_sequence_in_every_run_but_one() {
    /// The one row that does not preserve its sequence. See
    /// `the_cds_end_flush_pair_is_its_two_members_normalized_separately` for why.
    const PINNED_DEFECT: &str = "NM_TEST.1:c.[72del;72_*1insG]";

    let core = at_core();
    let frame = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    let served = frame.served().to_string();
    let runs = homopolymer_run_starts(&served);
    assert!(
        runs.len() > 10,
        "VACUOUS — the core must contain runs for this sweep to mean anything, found {}",
        runs.len()
    );

    let mut changed: Vec<(String, String)> = Vec::new();
    for start in &runs {
        let (start, first, next) = (*start, frame.label(*start), frame.label(*start + 1));
        let input = format!("NM_TEST.1:c.[{first}del;{first}_{next}insG]");
        let output = normalize_3prime(&frame, &input);
        // Deleting the run's first base and inserting `G` flush 3' of it leaves
        // one `G` where that base was; every other base is untouched.
        let expected = format!("{}G{}", &served[..start], &served[start + 1..]);
        match denotation_of(frame.provider(), frame.served(), &output) {
            Denotation::Sequence(applied) if applied == expected => {}
            Denotation::Sequence(_) => changed.push((input, output)),
            other => panic!("{input} -> {output} denotes nothing comparable: {other:?}"),
        }
    }

    let pinned: Vec<&String> = changed.iter().map(|(input, _)| input).collect();
    assert_eq!(
        pinned,
        vec![PINNED_DEFECT],
        "the set of flush pairs that change their sequence moved. Swept {} runs; \
         expected exactly the pinned CDS-end row to fail. If this row now PASSES, \
         the defect is fixed — delete the pin rather than widening it.",
        runs.len()
    );
}

/// **Question.** Why does that one row change its sequence, when each of the two
/// members is placed legally and the pair denotes an ordinary substitution?
///
/// **Because ferro normalizes the members separately and concatenates the
/// answers.** Measured on a core carrying `CCC` across `c.72`/`c.*1`/`c.*2`, so
/// the deletion is ambiguous across the CDS/3'UTR boundary:
///
/// ```text
/// c.72del            -> c.*2del         correct alone: 3'-most in the CCC run
/// c.72_*1insG        -> c.72delinsCG    correct alone: collapses the flush pair
/// c.[72del;72_*1insG] -> c.[72delinsCG;*2del]   <- exactly the two, side by side
/// ```
///
/// Each member's answer is right in isolation. Together they are wrong, because
/// the deletion's 3' shift runs over a homopolymer that its sibling has already
/// split: once `G` sits between `c.72` and `c.*1`, `CCC` is no longer a run in
/// the derived sequence and the deletion is no longer ambiguous. The pair
/// denotes `c.72C>G`; ferro's answer transposes the inserted base past the one
/// it should have replaced.
///
/// **This is the sequence-preservation class**, the one property no
/// representation argument can excuse — `background/basics.md:38` puts
/// "unequivocal" among the spec's four stated values, and a description denoting
/// bases the input did not is not a representation choice.
#[test]
fn the_cds_end_flush_pair_is_its_two_members_normalized_separately() {
    let frame = boundary_run_frame(83);
    let deletion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72del");
    let insertion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72_*1insG");
    let pair = normalize_3prime(&frame, "NM_TEST.1:c.[72del;72_*1insG]");

    // Each member is correct on its own.
    assert_eq!(deletion_alone, "NM_TEST.1:c.*2del");
    assert_eq!(insertion_alone, "NM_TEST.1:c.72delinsCG");

    // And the pair is precisely those two answers, side by side — which is the
    // whole defect, stated as an equality rather than asserted in prose.
    assert_eq!(
        pair, "NM_TEST.1:c.[72delinsCG;*2del]",
        "PINNED DEFECT — the pair denotes c.72C>G. Ferro reaches this by shifting \
         the deletion 3' through a run its sibling insertion has already split."
    );
    let concatenated = format!(
        "NM_TEST.1:c.[{};{}]",
        insertion_alone
            .strip_prefix("NM_TEST.1:c.")
            .expect("a c. description"),
        deletion_alone
            .strip_prefix("NM_TEST.1:c.")
            .expect("a c. description")
    );
    assert_eq!(
        pair, concatenated,
        "the pair's output IS the two members normalized independently"
    );
}

/// **Question.** The mirror shape at the 5'UTR/CDS boundary preserves its
/// sequence. Is that boundary handled correctly?
///
/// **No — it is masked.** With an identical `CCC` run straddling
/// `c.-1`/`c.1`/`c.2` and the identical flush shape, the lone deletion does not
/// shift **at all**: `c.-1del` normalizes to `c.-1del`, not to `c.2del`. With
/// nothing to shift there is nothing to transpose, so the pair survives by
/// accident rather than by handling.
///
/// **Why this matters for the fix.** It would be natural to read the failing
/// class as "the CDS end is special" and key a fix on that boundary. This test
/// is the counter-evidence: the two boundaries differ in whether the *shift*
/// happens, not in whether the members interfere. A fix keyed on the CDS end
/// would be keyed on the mask.
#[test]
fn the_five_prime_boundary_masks_the_same_per_member_defect() {
    let frame = boundary_run_frame(11);
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.-1del"),
        "NM_TEST.1:c.-1del",
        "PINNED — the lone deletion does not shift 3' across the 5'UTR/CDS \
         boundary, which is what masks the pair below"
    );
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.[-1del;-1_1insG]"),
        "NM_TEST.1:c.[-1del;-1_1insG]",
        "the pair is left alone — sequence-preserving, but by the mask above \
         rather than by collapsing to the substitution it denotes"
    );
}

/// A frame whose served sequence carries a three-base `CCC` run starting at
/// `run_at`, with both flanks broken so the run is exactly three.
///
/// Holding the run length and alphabet fixed is what makes the two boundary
/// tests above an A/B on the boundary alone.
fn boundary_run_frame(run_at: usize) -> Frame {
    let mut core: Vec<u8> = at_core().into_bytes();
    for offset in 0..3 {
        core[run_at + offset] = b'C';
    }
    if run_at > 0 {
        core[run_at - 1] = b'A';
    }
    if run_at + 3 < core.len() {
        core[run_at + 3] = b'A';
    }
    let core = String::from_utf8(core).expect("the core stays ASCII");
    Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core)
}

// ---------------------------------------------------------------------------
// The same per-member independence, emitting members that overlap
// ---------------------------------------------------------------------------

/// **Question.** The corpus's second rank-1 class is "output denotes no
/// sequence" — 10 outputs at 3' and 18 at 5' whose members claim overlapping
/// territory, so the description denotes nothing. Is it a separate defect from
/// the sequence-changing class?
///
/// **No — it is the same cause landing differently.** Every one of the 28 rows
/// is `cds-end` geometry, and the largest shape is the identical flush pair
/// `c.[72del;72_*1insA]` that
/// `the_cds_end_flush_pair_is_its_two_members_normalized_separately` dissects.
/// On the `AT` core the two independently-normalized members happen to tile
/// disjointly and denote the wrong bases; on the `ACGT` core they land on top of
/// each other and denote nothing at all. One cause, two symptoms, and which one
/// a row exhibits is a property of the neighbouring bases rather than of the
/// input.
///
/// That matters for the fix: driving `sequence_changed` to zero without
/// addressing member independence would move these rows between two rank-1
/// buckets rather than out of them.
#[test]
fn the_cds_end_flush_pair_can_also_emit_two_members_claiming_one_position() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);

        let deletion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72del");
        let insertion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72_*1insA");
        let pair = normalize_3prime(&frame, "NM_TEST.1:c.[72del;72_*1insA]");

        // Same decomposition as the sequence-changing row: the pair is its two
        // members normalized on their own.
        assert_eq!(deletion_alone, "NM_TEST.1:c.72del");
        assert_eq!(insertion_alone, "NM_TEST.1:c.72delinsCA");
        assert_eq!(
            pair, "NM_TEST.1:c.[72del;72delinsCA]",
            "PINNED DEFECT — both members claim c.72, so the allele denotes no \
             sequence at all ({strand:?} strand)"
        );

        // The defining property, asserted rather than described: the output is
        // not a partition of the reference, because two members claim c.72.
        assert!(
            pair.matches("72del").count() >= 1 && pair.contains("72delinsCA"),
            "the two members must both name c.72 for this to be the overlap class"
        );

        // Member order in the input must not change the answer.
        assert_eq!(
            normalize_3prime(&frame, "NM_TEST.1:c.[72_*1insA;72del]"),
            pair,
            "the defect is order-independent, so a fix cannot be an ordering rule"
        );
    }
}

/// **Question.** Does the overlap class only arise from the flush del+ins pair?
///
/// **No — a repeat typing reaches the same end.** `c.[72_*1del;*2_*3insTT]`
/// keeps its deletion and re-types the insertion as a four-unit `T` repeat
/// starting at `c.*1`: `c.[72_*1del;*1_*2T[4]]`. The deletion already claims
/// `c.*1`, so the repeat's tract overlaps its sibling and the allele again
/// denotes nothing.
///
/// **This is the typing stage widening a member past what the partition granted
/// it** — the same stage `fix/typing-must-not-widen-a-member` (#1571) addresses
/// for a different shape. Recorded here so the two are visibly one family: a
/// member's rendered extent must be bounded by the territory its partition
/// assigned, whichever edit type it renders as.
#[test]
fn a_repeat_typing_at_the_cds_end_overlaps_its_sibling_deletion() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        assert_eq!(
            normalize_3prime(&frame, "NM_TEST.1:c.[72_*1del;*2_*3insTT]"),
            "NM_TEST.1:c.[72_*1del;*1_*2T[4]]",
            "PINNED DEFECT — `72_*1del` already claims c.*1, so the `*1_*2T[4]` \
             tract overlaps it and the allele denotes no sequence ({strand:?})"
        );
    }
}
