//! Named regression tests promoted out of the exhaustive spec corpus.
//!
//! # Why these exist separately from the corpus
//!
//! **A corpus row can silently stop being generated.** That is this repository's
//! recorded blindness class, three times over: #1456 (every family paired members
//! on disjoint territory, so no conflicting allele existed and `0 of 18,432` was
//! reported three times as evidence), #1460 (20-mer cores, so nothing reached
//! `MAX_SPLIT_BLOCK` and a length-gated change was structurally invisible), #1478
//! (`Exon::with_genomic(1, 1, tx_len, …)` builds ONE exon with `CDS_START = 1`, so
//! no row could cross a junction or sit in the 5'UTR). Each was invisible to the
//! one before it.
//!
//! A named committed test cannot be un-generated by a later edit to the
//! generator. So: **the corpus for breadth, these for anything that ever went
//! red.**
//!
//! # These pin DEFECTS, not answers
//!
//! Every expectation below is what ferro produces on `main` at 35de96c8, and in
//! most cases it is **wrong**. Each test states the question, the answer the cited
//! clause gives, and what ferro does instead — the `KNOWN_DIVERGENT_INPUTS`
//! pattern, which exists so a deviation stays visible rather than rotting into an
//! assumption. When one is fixed, the assertion moves to the correct value in the
//! same commit and the comment says so.
//!
//! Not fixed here on purpose: a PR that both built this instrument and changed the
//! normalizer would have no baseline to measure the change against.

use ferro_hgvs::conformance::spec_corpus::{
    corpus_cores, denotation_of, Denotation, Frame, RefShape, DENSE_CORE_LEN,
};
use ferro_hgvs::reference::transcript::Strand;
use ferro_hgvs::{parse_hgvs, NormalizeConfig, Normalizer, ShuffleDirection};

/// The `AT`-alphabet core the corpus draws first. Chosen because a two-letter
/// alphabet makes long runs, which is where junction-crossing shifts live.
fn at_core() -> String {
    corpus_cores(1, DENSE_CORE_LEN).remove(0)
}

/// The `ACGT`-alphabet core, for rows whose defect needs a non-degenerate
/// neighbourhood.
fn acgt_core() -> String {
    corpus_cores(1, DENSE_CORE_LEN).remove(1)
}

/// Normalize `input` against `frame`, in the given direction.
fn normalize(frame: &Frame, input: &str, direction: ShuffleDirection) -> String {
    let variant = parse_hgvs(input).unwrap_or_else(|e| panic!("{input} must parse: {e}"));
    let normalizer = Normalizer::with_config(
        frame.provider().clone(),
        NormalizeConfig::default().with_direction(direction),
    );
    normalizer
        .normalize(&variant)
        .unwrap_or_else(|e| panic!("{input} must normalize: {e}"))
        .to_string()
}

/// Normalize in the default (3') direction.
fn normalize_3prime(frame: &Frame, input: &str) -> String {
    normalize(frame, input, ShuffleDirection::ThreePrime)
}

/// Normalize in the default (3') direction, surfacing the refusal instead of
/// panicking on it — for the rows whose adjudicated answer *is* a refusal.
fn normalize_3prime_result(frame: &Frame, input: &str) -> Result<String, String> {
    let variant = parse_hgvs(input).map_err(|e| e.to_string())?;
    Normalizer::with_config(
        frame.provider().clone(),
        NormalizeConfig::default().with_direction(ShuffleDirection::ThreePrime),
    )
    .normalize(&variant)
    .map(|v| v.to_string())
    .map_err(|e| e.to_string())
}

// ---------------------------------------------------------------------------
// The 3' shift crosses an exon junction on a MINUS-strand transcript
// ---------------------------------------------------------------------------

/// **Question.** May the 3' shift move a deletion out of an exon and into the
/// following intron?
///
/// **Yes — the shift is legal. It was the ACCESSION that was not, and #1704 fixed
/// that.** This doc comment previously said "the clauses say no, twice" and cited
/// `general.md:44` as forbidding the shift. That was backwards, and it mattered:
/// it named a target that would implement an exception the spec explicitly
/// withholds.
///
/// `general.md:44` defers to `background/numbering.md`, which scopes its
/// exception twice — `:23` applies it to **exon/exon** junctions "where shifting
/// the variant 3' would place it in the **next exon**", and `:26` states that it
/// "**does not apply** to a deletion/duplication around **exon/intron and
/// intron/exon** junctions". This row is exactly the exon→intron case `:26`
/// excludes, and ferro already blocks the exon→exon case the exception covers.
///
/// What IS violated is `checklist.md:20`: "NM reference sequences cover mature
/// transcripts and **do not contain** intron and gene flanking sequences, and can
/// only be used to describe variants in introns using a `c.` prefix when a
/// genomic reference sequence is given". The output used to name a position its
/// own accession could not express; converging on the clamped `c.20del` would
/// have reverted #670, so #1704 took the other route and re-parents onto the
/// genomic wrapper the crossing had already resolved —
/// `NC_SYNTH.1(NM_TEST.1):c.20+2del`. The coordinate is unchanged.
///
/// **The strand is a confound, not a finding.** The plus/minus difference below
/// is real but is a property of the fixture: the provider writes a literal
/// `GATTACA` intron and reverse-complements only the exon blocks, so against an
/// `AT` core `G` never continues a run and `AA` always does. Hold the
/// transcript-direction intron fixed and both strands agree — see
/// `defect_371_transcript_exit.rs`, whose `junction_provider` takes the intron as
/// a parameter for precisely this reason.
///
/// This was the largest single class the corpus found — **371 outputs on the 3'
/// direction and 0 on the 5'** — and it is structurally invisible to a
/// single-exon fixture, which is #1478 exactly. The 0 at 5' is a claim about the
/// code, not the corpus: all three copies of the #670 gate are guarded on
/// `ThreePrime` with no 5' mirror. All 371 now carry the wrapper and are counted
/// by `spec_conformance_axis`'s `outputs_intronic_under_a_genomic_wrapper`;
/// `outputs_leaving_the_transcript` is pinned at **0**.
#[test]
fn a_minus_strand_junction_shift_leaves_the_transcript() {
    let core = at_core();
    let plus = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    let minus = Frame::build(RefShape::CodingMultiExon(Strand::Minus), &core);

    // The contrast, NOT the target: on the plus strand the shift stops inside
    // the exon. That is a property of this fixture's intron, not a clamp the
    // minus strand is failing to apply — see the doc comment.
    assert_eq!(
        normalize_3prime(&plus, "NM_TEST.1:c.17del"),
        "NM_TEST.1:c.20del",
        "the plus-strand contrast: same design, intron that does not continue the run"
    );

    // The defect: on the minus strand it walks two bases into the intron.
    assert_eq!(
        normalize_3prime(&minus, "NM_TEST.1:c.17del"),
        "NC_SYNTH.1(NM_TEST.1):c.20+2del",
        "the SHIFT is legal (numbering.md:26 withholds general.md:44's exception from \
         exon/intron junctions) and the ACCESSION now satisfies checklist.md:20, which \
         requires a genomic reference for an intronic position (#1704). NOT c.20del, which \
         would implement an exception the spec explicitly excludes and would revert #670."
    );
}

/// **Question.** What happens when *two* members of one allele both shift past
/// the same junction?
///
/// **They land on the same base.** `c.[20del;17del]` becomes
/// `c.[20+2del;20+2del]` — two identical members, which denotes no sequence at
/// all: the second deletion has nothing left to delete. `general.md:58`'s
/// neighbourhood is the closest clause ("descriptions removing part of a
/// reference sequence and replacing it with part of the same sequence are not
/// allowed"), but the plainer statement is that a description must denote one
/// sequence, and this one denotes none.
///
/// Kept separate from the single-member case because it is a *different* failure:
/// the single-member output is expressible-but-prohibited, this one is
/// self-contradictory, and only a multi-member allele can produce it.
#[test]
fn two_members_shifting_past_one_junction_collide_into_identical_members() {
    let core = at_core();
    let minus = Frame::build(RefShape::CodingMultiExon(Strand::Minus), &core);

    let output = normalize_3prime(&minus, "NM_TEST.1:c.[20del;17del]");
    assert_eq!(
        output, "NC_SYNTH.1(NM_TEST.1):c.[20+2del;20+2del]",
        "PINNED DEFECT — two identical members denote no sequence. Correct output: \
         NM_TEST.1:c.19_20del, which is what the plus-strand control gives. #1704 fixed the \
         ACCESSION half of this row (the wrapper is now present and correct) and deliberately \
         did not touch the collision, which is a separate defect: the accession was invalid \
         AND the description denotes nothing, and only the first is checklist.md:20's."
    );

    // The plus-strand control, so the strand-specificity is pinned too and a
    // future fix cannot quietly break the side that works.
    let plus = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    assert_eq!(
        normalize_3prime(&plus, "NM_TEST.1:c.[20del;17del]"),
        "NM_TEST.1:c.19_20del"
    );
}

// ---------------------------------------------------------------------------
// Conflicting alleles are normalized instead of refused (#1456's shape)
// ---------------------------------------------------------------------------

/// **Question.** Must a description whose members claim the same reference
/// territory be refused?
///
/// **Yes — it denotes no sequence.** `general.md:58`: "descriptions removing part
/// of a reference sequence and replacing it with part of the same sequence are not
/// allowed (e.g., `NM_004006.2:c.[762_768del;767_774dup]`)". Ferro already
/// enforces exactly that spelling — a `del` plus an overlapping `dup` is rejected
/// at parse with "Self-cancelling allele" — but the check is keyed on that pair of
/// edit types, so a `del` plus an overlapping `del` sails through.
///
/// Three geometries, all accepted, **72 rows in total**. Every one of them was
/// structurally impossible to generate before #1456: the designed corpus paired
/// members on disjoint territory only, and reported `0 of 18,432` three times.
#[test]
fn conflicting_member_geometries_are_normalized_instead_of_refused() {
    let core = at_core();
    let frame = Frame::build(RefShape::CodingSingleExon, &core);
    let served = frame.served();

    for (geometry, input) in [
        // One member's footprint strictly inside another's.
        ("nested", "NM_TEST.1:c.[9_12del;10_11del]"),
        // Footprints that partially intersect.
        ("overlapping", "NM_TEST.1:c.[9_12del;11_14del]"),
        // Two pure insertions at one interbase, which have no order.
        ("coincident insertions", "NM_TEST.1:c.[8_9insAC;8_9insCC]"),
    ] {
        // First, the premise: the input really does denote no sequence. Without
        // this the test would be asserting a preference rather than a defect.
        assert_eq!(
            denotation_of(frame.provider(), served, input),
            Denotation::NoSequence,
            "{geometry}: {input} must denote no sequence for this test to mean anything"
        );

        // The defect: ferro accepts it and hands back a description.
        let output = normalize_3prime(&frame, input);
        assert_eq!(
            output, input,
            "PINNED DEFECT ({geometry}) — general.md:58 makes a description that claims one \
             territory twice invalid, and ferro already rejects the del+dup spelling the clause \
             names. Correct behaviour: refuse."
        );
    }
}

// ---------------------------------------------------------------------------
// Absolute prohibitions accepted, and re-emitted
// ---------------------------------------------------------------------------

/// **Question.** Are the shapes the checklist calls "not allowed" rejected?
///
/// **Two are still not**, and each is accepted both standalone and inside an
/// allele, then emitted again unchanged — so the prohibition is enforced on
/// neither the input nor the output side. **The third, `checklist.md:33`'s
/// `ins6`, is now refused (#1789)** and is asserted here as an
/// adjudicated-correct guard rather than as a pinned defect.
///
/// The clauses, verbatim:
///
/// - `checklist.md:33` — "Describing a variant as `c.5439_5430ins6` is not
///   allowed, the inserted sequence (for `ins6`, e.g., `TGCCAT`) should be
///   specified." **Enforced since #1789.** Note the spec's own example is
///   *separately* refused for its inverted range (5439 > 5430), which is a
///   different check that happens to catch it — which is precisely why the
///   acceptance stayed invisible, and why the row asserted here has a valid
///   range instead.
/// - `checklist.md:16` — a genomic reference "can not have nucleotides with
///   additions like a `+`, `-`, or `*`". **Closed by #1628**: both offset shapes
///   are refused now, so the two rows below are inverted rather than removed.
/// - `checklist.md:45` — "Not correct is `c.12-14del`, this describes a deletion
///   of nucleotide -14 in the intron directly 5' of nucleotide `c.12`". On a
///   genomic axis there is no intron to read it into, so the shape has no legal
///   reading at all. **Closed by #1628** on the same rule.
#[test]
fn absolute_prohibitions_are_accepted_and_re_emitted() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    let genomic = Frame::build(RefShape::Genomic, &core);

    // `ins6`: an insertion that states a LENGTH instead of a sequence. Refused
    // at normalize in every mode since #1789 — the full three-mode, two-stage
    // guard (and the `ins(6)` spelling, and the `r.` axis) is in
    // `issue_1789_insertion_size_count.rs`; what is asserted here is the corpus
    // row itself, in the file that owns the corpus's named regressions.
    let ins6 = parse_hgvs("NM_TEST.1:c.10_11ins6").expect("the grammar admits it");
    let err = Normalizer::with_config(
        coding.provider().clone(),
        NormalizeConfig::default().with_direction(ShuffleDirection::ThreePrime),
    )
    .normalize(&ins6)
    .expect_err("checklist.md:33 — a count names no bases to normalize")
    .to_string();
    assert!(
        err.contains("W3029"),
        "the refusal must name the size-count finding; got: {err}"
    );

    // The two genomic-offset shapes are no longer accepted at all (#1628), so
    // they are asserted here as REFUSALS rather than dropped: this test is the
    // record of what the clause census used to hold, and a row silently leaving
    // it would read as the census shrinking rather than as a defect closing.
    // The per-mode guard is `genomic_axis_offset_prohibition`.
    for (input, clause) in [
        (
            "NC_TEST.1:g.266+2del",
            "numbering.md:6 / checklist.md:16 — a `g.` reference admits no `+` addition",
        ),
        (
            "NC_TEST.1:g.266-268del",
            "checklist.md:45 — the hyphen form is `Not correct`, and on a genomic axis it \
             has no intronic reading either",
        ),
    ] {
        let refusal = normalize_3prime_result(&genomic, input).expect_err(&format!(
            "ADJUDICATED CORRECT, REGRESSED: `{input}` must be refused ({clause})"
        ));
        assert!(
            refusal.contains("W4009"),
            "the refusal of `{input}` must be the genomic-offset finding; got: {refusal}"
        );
    }
}

/// **Question.** Does a prohibited member become *less* visible when it sits
/// inside an allele?
///
/// **It used to, and that was the more interesting half.** The allele form is
/// checked separately because a hygiene check that runs once per description
/// rather than once per member is a failure mode with its own signature, and the
/// corpus generates both forms of every prohibition precisely to tell them
/// apart.
///
/// **#1789 closed this one, and the allele arm is what proves the fix is not
/// per-description.** The refusal is keyed on the AST and walks every member, so
/// the offending member is reached inside a cis allele exactly as it is
/// standalone. Kept as a guard rather than deleted: a future re-implementation
/// that checks only the top-level description would pass the standalone row and
/// fail here, which is the whole reason this row exists.
#[test]
fn a_prohibited_member_inside_an_allele_is_also_accepted() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    let allele = parse_hgvs("NM_TEST.1:c.[10_11ins6;9del]").expect("the grammar admits it");
    let err = Normalizer::with_config(
        coding.provider().clone(),
        NormalizeConfig::default().with_direction(ShuffleDirection::ThreePrime),
    )
    .normalize(&allele)
    .expect_err("the offending MEMBER must be reached, not only a top-level description")
    .to_string();
    assert!(
        err.contains("W3029"),
        "the refusal must name the size-count finding; got: {err}"
    );

    // The control: the same allele with the offending member's payload spelled
    // conformantly still normalizes, so the refusal above is attributable to the
    // payload's form and not to the allele. The two flush members merge into one
    // `delins` (`substitution.md:32`) and the `N[6]` payload expands into a
    // literal run on the way, which is ordinary normalization and not part of
    // what this row measures.
    assert_eq!(
        normalize_3prime(&coding, "NM_TEST.1:c.[10_11insN[6];9del]"),
        "NM_TEST.1:c.9_10delinsANNNNNN",
        "the conformant spelling of the same claim must still round-trip"
    );
}

/// **Question.** Is `X` a nucleotide?
///
/// **No, and ferro now refuses it (#1627).** `background/standards.md` lists it
/// in the DNA symbol table and then footnotes it at `:39` — "† used in alignment
/// only" — alongside `-`. Neither is a base a description may state, which is
/// the decided `rulings[alignment-only-symbol-in-a-description]`; `X` is not one
/// of the 15 symbols `general.md:48` admits.
///
/// **This was a PINNED FINDING and is now an adjudicated-correct guard.** The
/// corpus grades the row `conditional` rather than `absolute` because the
/// footnote states a scope rather than using prohibitive words, and the ruling
/// records that the grading is moot either way — the alphabet half of rank-1
/// validity settles it on its own.
///
/// The full three-mode, two-stage guard (including the embedded shapes this
/// corpus does not generate) lives in `corpus_prohibited_inputs::`
/// `an_alignment_only_symbol_is_refused_in_every_mode_for_both_x_and_dash`.
/// What is asserted here is the corpus row itself, in the file that owns the
/// corpus's named regressions.
#[test]
fn an_alignment_only_x_base_is_refused_rather_than_re_emitted() {
    let core = at_core();
    let coding = Frame::build(RefShape::CodingSingleExon, &core);
    let variant = parse_hgvs("NM_TEST.1:c.10delinsX").expect("lenient parse accepts it");
    let err = Normalizer::with_config(
        coding.provider().clone(),
        NormalizeConfig::default().with_direction(ShuffleDirection::ThreePrime),
    )
    .normalize(&variant)
    .expect_err("standards.md:39 — normalization cannot resolve a masked base")
    .to_string();
    assert!(
        err.contains("W3028"),
        "the refusal must name the alignment-only-symbol finding; got: {err}"
    );

    // The sibling symbol is refused by the GRAMMAR rather than by that rule, and
    // the pair is still worth pinning together: they are footnoted identically
    // and reach the refusal by different routes, so `-` is not the template the
    // `X` fix copied.
    assert!(
        parse_hgvs("NM_TEST.1:c.10delins-").is_err(),
        "`-` is refused by the grammar, though standards.md:39 footnotes both"
    );
}

/// **Question.** May an intronic position be written against a bare transcript
/// accession?
///
/// **No.** `checklist.md:20`: "NM reference sequences cover mature transcripts and
/// **do not contain** intron and gene flanking sequences, and can only be used to
/// describe variants in introns using a `c.` prefix when a genomic reference
/// sequence is given on which the coding DNA reference sequence is annotated,
/// e.g., `NC_000023.10(NM_004006.2):c.94-2A>G` or `LRG_199t1:c.94-2A>G`."
///
/// Ferro accepts the bare form. This is why the corpus writes its intronic
/// idempotency rows against `NC_SYNTH.1(NM_TEST.1)` and generates the bare form
/// only as a shape that ought to be refused: a bare `NM_…:c.123+65del` is an
/// **invalid input**, not a test case.
#[test]
fn a_bare_transcript_accession_accepts_an_intronic_position() {
    let core = at_core();
    let frame = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.20+2del"),
        "NM_TEST.1:c.20+2del",
        "PINNED FINDING — checklist.md:20 permits an intronic `c.` position only with a genomic \
         wrapper. Correct behaviour: refuse, or demand the NC_(NM_) form."
    );
    // The wrapper form is what the spec asks for, and ferro accepts it too — so
    // the fix is a refusal of the bare form, not support for the wrapper.
    assert!(parse_hgvs("NC_SYNTH.1(NM_TEST.1):c.20+2del").is_ok());
}

// ---------------------------------------------------------------------------
// The CDS/3'UTR boundary
// ---------------------------------------------------------------------------

/// **Question.** Is an insertion at the CDS/3'UTR boundary a fixed point?
///
/// **Yes, since #1650 — this was the pinned defect and it is now the guard.**
///
/// It used to take two passes: `c.*1delinsCTT` normalized to `c.72_*1insCT`,
/// which normalized *again* to `c.72delinsCCT`. Idempotency is not a spec clause
/// — it is an invariant of any normalizer, and `FERRO_ASSERT_IDEMPOTENT` exists
/// to police it — so it was pinned as a defect with no citation to make.
///
/// The cause was the sequence-first pass refusing every member on the far side
/// of `cds_end`, so the second pass answered a question the first could not see.
/// `merge::ExtendedBody` lets the first pass read both sides, and it now reaches
/// `c.72delinsCCT` in **one** step. `spec_conformance_axis`'s
/// `non_idempotent_outputs` goes 4 -> 0 with this, in both directions.
///
/// **Renamed with the flip**, from `..._is_not_a_fixed_point`. An earlier draft
/// kept the old name on the ground that `ci.yml`'s `ORACLE_EXCLUDE` cites it —
/// **it does not**: that variable excludes whole modules (`test(spec_corpus_regressions)`),
/// so no rename can break it. The one real cross-reference is the header comment
/// in `scripts/run_oracle_suite.sh`, which names this test explicitly and is
/// updated in the same commit. A test whose name asserts the opposite of its
/// body is the same defect class as an assertion weaker than its stated
/// contract.
///
/// The shape needs a transcript with a real 3'UTR, which a `CDS_START = 1`
/// single-exon fixture cannot have (#1478). It reproduces on both strands.
#[test]
fn an_insertion_at_the_cds_end_is_a_fixed_point() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        let once = normalize_3prime(&frame, "NM_TEST.1:c.*1delinsCTT");
        assert_eq!(once, "NM_TEST.1:c.72delinsCCT");
        let twice = normalize_3prime(&frame, &once);
        assert_eq!(
            twice, once,
            "`{once}` must be its own fixed point on the {strand:?} strand — this is \
             the invariant the row used to violate, asserted rather than pinned."
        );
    }
}

/// **Question.** What does a deletion flush against an insertion at the CDS/3'UTR
/// boundary denote, and does ferro preserve it?
///
/// **It does not.** `c.[72del;72_*1insA]` deletes the last CDS base and inserts
/// `A` at the interbase immediately 3' of it, which denotes
/// `…tx[..83] + "A" + tx[84..]` — the same sequence as `c.72delinsA`. Ferro
/// returns `c.[72delinsTA;*2del]`, which denotes different bases: it keeps a base
/// the input deleted and deletes one the input did not touch.
///
/// **Sequence preservation is the one property no representation argument can
/// excuse**, so this is the most serious of the four rows in its class. It is a
/// `CoincidentEndpoint` geometry — two members sharing an endpoint without their
/// footprints intersecting — which is legal, and which the designed corpus could
/// not build before #1456.
///
/// Honest caveat, recorded rather than glossed: the corpus's applier reads a
/// deletion and a flush insertion in one order (longer deletion first, then the
/// zero-width member), and one *could* argue an insertion anchored on a base the
/// same allele deletes is itself ill-defined. If that reading wins, the fix is a
/// refusal rather than a different output — but it cannot be the output ferro
/// gives, which denotes a third sequence that neither reading produces.
#[test]
fn a_deletion_flush_against_an_insertion_at_the_cds_end_changes_the_sequence() {
    let core = at_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        let input = "NM_TEST.1:c.[72del;72_*1insA]";
        let expected = match denotation_of(frame.provider(), frame.served(), input) {
            Denotation::Sequence(sequence) => sequence,
            other => panic!("the input must denote a sequence, got {other:?}"),
        };
        let output = normalize_3prime(&frame, input);
        assert_eq!(
            output, "NM_TEST.1:c.*1T>A",
            "PINNED DEFECT on the {strand:?} strand. **Re-blessed by #1650, and the \
             defect is NOT fixed** — only its spelling moved, from the two-member \
             `c.[72delinsTA;*2del]` to this single substitution. Both denote the same \
             wrong bases, which is why `spec_conformance_axis`'s `sequence_changed` \
             is still 4 either side; what #1650 changed is that the wrong answer is \
             now reached in one pass instead of two."
        );
        assert_ne!(
            denotation_of(frame.provider(), frame.served(), &output),
            Denotation::Sequence(expected),
            "if this now holds, the defect is FIXED — move the assertion above to the \
             sequence-preserving output and re-bless the axis census in the same commit"
        );
    }
}

// ---------------------------------------------------------------------------
// A negative result, pinned because it is worth as much as a defect
// ---------------------------------------------------------------------------

/// **Question.** Does ferro implement rejected proposal SVD-WG010 — a separation
/// floor of two on an axis with no reading frame?
///
/// **No, and this pins that.** `general.md:36-39` announces a "new
/// recommendation" that "two variants separated by less than two nucleotides
/// should be described as a 'delins'". That note is **stale**: it describes
/// SVD-WG010, opened 2021-05-15 and closed **rejected** 2021-07-31
/// (`consultation/SVD-WG010.md:8`, "The proposal has been **rejected**"). The live
/// rule is `general.md:34`'s floor of one, with `:35`'s codon exception — which
/// cannot reach a frameless axis at all, being conditioned on "together affecting
/// one amino acid".
///
/// This is not hypothetical: `coalesce_coding_frame_separation` once applied the
/// floor of two on a frameless axis and emitted SVD-WG010's own worked example.
/// The corpus measures **0 violations over 210 rows carrying the shape**, and the
/// denominator is asserted non-zero — `0 of 0` is what a rebuilt #1456 looks like.
///
/// Recorded per `CLAUDE.md`'s "record what was refuted, not only what was
/// decided": a measurement that killed a plausible belief is worth as much as the
/// ruling, because the belief recurs.
#[test]
fn a_frameless_irreducible_separation_of_one_is_not_merged() {
    let core = acgt_core();
    let genomic = Frame::build(RefShape::Genomic, &core);
    let served = genomic.served();

    // Two substitutions separated by one unchanged base. A substitution cannot
    // shift, so the separation is irreducible by construction — which is the
    // condition that distinguishes rejected SVD-WG010 from the 3' rule closing a
    // gap inside a run.
    let first = genomic.label(genomic.core_offset() + 8);
    let third = genomic.label(genomic.core_offset() + 10);
    let base_at = |offset: usize| &served[genomic.core_offset() + offset..][..1];
    let alt = |base: &str| if base == "A" { "C" } else { "A" };
    let input = format!(
        "NC_TEST.1:g.[{first}{}>{};{third}{}>{}]",
        base_at(8),
        alt(base_at(8)),
        base_at(10),
        alt(base_at(10))
    );

    let output = normalize_3prime(&genomic, &input);
    let parsed = parse_hgvs(&output).expect("the output re-parses");
    let members = match &parsed {
        ferro_hgvs::HgvsVariant::Allele(allele) => allele.variants.len(),
        _ => 1,
    };
    assert!(
        members >= 2,
        "merging {input} into `{output}` would implement REJECTED SVD-WG010; general.md:34 \
         says two variants separated by one or more nucleotides are described individually"
    );
}

// ---------------------------------------------------------------------------
// A flush deletion + insertion pair is normalized per member, and the members
// interfere
// ---------------------------------------------------------------------------

/// Every homopolymer-run start in the corpus's `AT` core, as `(index, run end)`.
///
/// A run is where a lone deletion is ambiguous under the 3'rule, so it is
/// exactly where a sibling insertion can be transposed past. Derived from the
/// served sequence rather than listed, so the cases track the core.
fn homopolymer_run_starts(served: &str) -> Vec<usize> {
    let bytes = served.as_bytes();
    let mut starts = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let mut j = i;
        while j + 1 < bytes.len() && bytes[j + 1] == bytes[i] {
            j += 1;
        }
        if j > i {
            starts.push(i);
        }
        i = j + 1;
    }
    starts
}

/// **Question.** `c.[Ndel;N_N+1insG]` deletes one base and inserts `G` at the
/// interbase immediately 3' of it, which denotes exactly `c.NG>...` — a
/// substitution. Does ferro preserve that sequence wherever the pair is placed?
///
/// **Everywhere but one place.** Sweeping the flush pair across all 23
/// homopolymer runs in the `AT` core — the only positions where the deletion is
/// ambiguous enough to move — 22 collapse to the substitution and one does not:
/// `c.[72del;72_*1insG]`, at the CDS/3'UTR boundary, comes out as
/// `c.[72delinsTG;*2del]`, which denotes the same bases in the wrong ORDER.
///
/// **The run length is not the variable, and neither is the boundary.** Runs of
/// two through seven all pass, including three-base runs at indices 45, 65 and
/// 70; both UTRs pass internally. The one failing row is pinned below rather
/// than excluded, and this test **fails when it starts passing** — that is
/// deliberate, in the `KNOWN_DIVERGENT_INPUTS` tradition: a fixed deviation must
/// not rot in a list unnoticed. When it goes green, delete the pin.
#[test]
fn a_flush_deletion_and_insertion_preserves_the_sequence_in_every_run_but_one() {
    /// The one row that does not preserve its sequence. See
    /// `the_cds_end_flush_pair_is_its_two_members_normalized_separately` for why.
    const PINNED_DEFECT: &str = "NM_TEST.1:c.[72del;72_*1insG]";

    let core = at_core();
    let frame = Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core);
    let served = frame.served().to_string();
    let runs = homopolymer_run_starts(&served);
    // The denominator is PINNED, not floored. `> 10` would let the core shrink
    // to eleven runs and keep this sweep green over less than half its
    // territory, while `pinned == vec![PINNED_DEFECT]` still held — which is the
    // #1460 shrink-the-denominator failure this file's module doc names, applied
    // to this test's own denominator. The doc comment above claims "all 23
    // homopolymer runs in the `AT` core", so 23 is what it must be: a change to
    // `DENSE_CORE_LEN` or the core alphabet has to move this number
    // deliberately, in a reviewable diff.
    assert_eq!(
        runs.len(),
        23,
        "the sweep's denominator moved — the doc above claims all 23 homopolymer runs in the \
         `AT` core. If the core legitimately changed, update both the count and the doc; do NOT \
         relax this to an inequality, which is how a sweep silently narrows"
    );

    let mut changed: Vec<(String, String)> = Vec::new();
    for start in &runs {
        let (start, first, next) = (*start, frame.label(*start), frame.label(*start + 1));
        let input = format!("NM_TEST.1:c.[{first}del;{first}_{next}insG]");
        let output = normalize_3prime(&frame, &input);
        // Deleting the run's first base and inserting `G` flush 3' of it leaves
        // one `G` where that base was; every other base is untouched.
        let expected = format!("{}G{}", &served[..start], &served[start + 1..]);
        match denotation_of(frame.provider(), frame.served(), &output) {
            Denotation::Sequence(applied) if applied == expected => {}
            Denotation::Sequence(_) => changed.push((input, output)),
            other => panic!("{input} -> {output} denotes nothing comparable: {other:?}"),
        }
    }

    let pinned: Vec<&String> = changed.iter().map(|(input, _)| input).collect();
    assert_eq!(
        pinned,
        vec![PINNED_DEFECT],
        "the set of flush pairs that change their sequence moved. Swept {} runs; \
         expected exactly the pinned CDS-end row to fail. If this row now PASSES, \
         the defect is fixed — delete the pin rather than widening it.",
        runs.len()
    );
}

/// **Question.** Why does that one row change its sequence, when each of the two
/// members is placed legally and the pair denotes an ordinary substitution?
///
/// **The answer CHANGED with #1650, and the old one is kept because it is what
/// makes the new one legible.** Measured on a core carrying `CCC` across
/// `c.72`/`c.*1`/`c.*2`, so the deletion is ambiguous across the CDS/3'UTR
/// boundary:
///
/// ```text
/// c.72del             -> c.*2del        correct alone: 3'-most in the CCC run
/// c.72_*1insG         -> c.72delinsCG   correct alone: collapses the flush pair
/// c.[72del;72_*1insG] -> c.[72delinsCG;*2del]   BEFORE #1650: exactly the two, side by side
///                     -> c.*1C>G                AFTER  #1650: one re-derived member
/// ```
///
/// Before #1650 the explanation was **concatenation**: the sequence-first pass
/// refused every group with a member past `cds_end`, so each member was
/// normalized in isolation and the answers were placed side by side. Each is
/// right alone and they are wrong together, because the deletion's 3' shift runs
/// over a homopolymer its sibling has already split — once `G` sits between
/// `c.72` and `c.*1`, `CCC` is no longer a run in the derived sequence.
///
/// #1650 lets the pass read both sides of `cds_end`, so the group **is** now
/// re-derived rather than concatenated, and the concatenation identity below is
/// asserted to have stopped holding. **The class did not move with it.** The
/// pair denotes `c.72C>G` — `CCC` becomes `GCC` — and both the old answer and
/// the new one denote `CGC`. `spec_conformance_axis`'s `sequence_changed` reads
/// **4 either side**, which is the measurement that says so over the whole
/// corpus rather than over this row.
///
/// **So the diagnosis this module shipped is now half wrong, and that is the
/// finding.** "Ferro concatenates independently-normalized members" was never
/// the root cause; it was the route. The root cause survives re-derivation,
/// which localises it to how the boundary run is partitioned rather than to
/// where the members came from. Tracked in the sibling test's own pin, which
/// still fires.
///
/// **This is the sequence-preservation class**, the one property no
/// representation argument can excuse — `background/basics.md:38` puts
/// "unequivocal" among the spec's four stated values, and a description denoting
/// bases the input did not is not a representation choice.
#[test]
fn the_cds_end_flush_pair_is_its_two_members_normalized_separately() {
    let frame = boundary_run_frame(83);
    let deletion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72del");
    let insertion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72_*1insG");
    let pair = normalize_3prime(&frame, "NM_TEST.1:c.[72del;72_*1insG]");

    // Each member is still correct on its own, and #1650 does not touch either —
    // a lone member is not a group the extension can admit.
    assert_eq!(deletion_alone, "NM_TEST.1:c.*2del");
    assert_eq!(insertion_alone, "NM_TEST.1:c.72delinsCG");

    assert_eq!(
        pair, "NM_TEST.1:c.*1C>G",
        "PINNED DEFECT — the pair denotes c.72C>G (`CCC` -> `GCC`) and this answer \
         denotes `CGC`. Re-blessed by #1650 from `c.[72delinsCG;*2del]`, which \
         denotes the same wrong bases; the spelling moved and the class did not."
    );

    let concatenated = format!(
        "NM_TEST.1:c.[{};{}]",
        insertion_alone
            .strip_prefix("NM_TEST.1:c.")
            .expect("a c. description"),
        deletion_alone
            .strip_prefix("NM_TEST.1:c.")
            .expect("a c. description")
    );
    assert_ne!(
        pair, concatenated,
        "the pair is now RE-DERIVED, not concatenated — if this equality comes \
         back, #1650's extension has stopped admitting the group and the \
         explanation in this test's doc comment reverts with it"
    );
}

/// **Question.** The mirror shape at the 5'UTR/CDS boundary preserves its
/// sequence. Is that boundary handled correctly?
///
/// **No — it is masked.** With an identical `CCC` run straddling
/// `c.-1`/`c.1`/`c.2` and the identical flush shape, the lone deletion does not
/// shift **at all**: `c.-1del` normalizes to `c.-1del`, not to `c.2del`. With
/// nothing to shift there is nothing to transpose, so the pair survives by
/// accident rather than by handling.
///
/// **Why this matters for the fix.** It would be natural to read the failing
/// class as "the CDS end is special" and key a fix on that boundary. This test
/// is the counter-evidence: the two boundaries differ in whether the *shift*
/// happens, not in whether the members interfere. A fix keyed on the CDS end
/// would be keyed on the mask.
#[test]
fn the_five_prime_boundary_masks_the_same_per_member_defect() {
    let frame = boundary_run_frame(11);
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.-1del"),
        "NM_TEST.1:c.-1del",
        "PINNED — the lone deletion does not shift 3' across the 5'UTR/CDS \
         boundary, which is what masks the pair below"
    );
    assert_eq!(
        normalize_3prime(&frame, "NM_TEST.1:c.[-1del;-1_1insG]"),
        "NM_TEST.1:c.[-1del;-1_1insG]",
        "the pair is left alone — sequence-preserving, but by the mask above \
         rather than by collapsing to the substitution it denotes"
    );
}

/// A frame whose served sequence carries a three-base `CCC` run starting at
/// `run_at`, with both flanks broken so the run is exactly three.
///
/// Holding the run length and alphabet fixed is what makes the two boundary
/// tests above an A/B on the boundary alone.
fn boundary_run_frame(run_at: usize) -> Frame {
    let mut core: Vec<u8> = at_core().into_bytes();
    for offset in 0..3 {
        core[run_at + offset] = b'C';
    }
    if run_at > 0 {
        core[run_at - 1] = b'A';
    }
    if run_at + 3 < core.len() {
        core[run_at + 3] = b'A';
    }
    let core = String::from_utf8(core).expect("the core stays ASCII");
    Frame::build(RefShape::CodingMultiExon(Strand::Plus), &core)
}

// ---------------------------------------------------------------------------
// The same per-member independence, emitting members that overlap
// ---------------------------------------------------------------------------

/// **Question.** The corpus's second rank-1 class is "output denotes no
/// sequence" — 10 outputs at 3' and 18 at 5' whose members claim overlapping
/// territory, so the description denotes nothing. Is it a separate defect from
/// the sequence-changing class?
///
/// **No — it is the same cause landing differently.** Every one of the 28 rows
/// is `cds-end` geometry, and the largest shape is the identical flush pair
/// `c.[72del;72_*1insA]` that
/// `the_cds_end_flush_pair_is_its_two_members_normalized_separately` dissects.
/// On the `AT` core the two independently-normalized members happen to tile
/// disjointly and denote the wrong bases; on the `ACGT` core they land on top of
/// each other and denote nothing at all. One cause, two symptoms, and which one
/// a row exhibits is a property of the neighbouring bases rather than of the
/// input.
///
/// That matters for the fix: driving `sequence_changed` to zero without
/// addressing member independence would move these rows between two rank-1
/// buckets rather than out of them.
#[test]
fn the_cds_end_flush_pair_can_also_emit_two_members_claiming_one_position() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);

        let deletion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72del");
        let insertion_alone = normalize_3prime(&frame, "NM_TEST.1:c.72_*1insA");
        let pair = normalize_3prime(&frame, "NM_TEST.1:c.[72del;72_*1insA]");

        // Same decomposition as the sequence-changing row: the pair is its two
        // members normalized on their own.
        assert_eq!(deletion_alone, "NM_TEST.1:c.72del");
        assert_eq!(insertion_alone, "NM_TEST.1:c.72delinsCA");
        assert_eq!(
            pair, "NM_TEST.1:c.[72del;72delinsCA]",
            "PINNED DEFECT — both members claim c.72, so the allele denotes no \
             sequence at all ({strand:?} strand)"
        );

        // The defining property, asserted through the INDEPENDENT oracle rather
        // than by inspecting the string. The previous check —
        // `pair.matches("72del").count() >= 1 && pair.contains("72delinsCA")` —
        // was tautological: it re-read the two substrings the `assert_eq!` above
        // had just pinned, so it could not fail while that one passed, and it
        // asked nothing about denotation at all. This is the pattern
        // `conflicting_member_geometries_are_normalized_instead_of_refused`
        // already uses above: establish the premise with `denotation_of`, then
        // pin the spelling.
        assert_eq!(
            denotation_of(frame.provider(), frame.served(), &pair),
            Denotation::NoSequence,
            "{strand:?}: the emitted allele must denote no sequence — that is what makes this \
             the overlap class rather than a spelling preference"
        );

        // Member order in the input must not change the answer.
        assert_eq!(
            normalize_3prime(&frame, "NM_TEST.1:c.[72_*1insA;72del]"),
            pair,
            "the defect is order-independent, so a fix cannot be an ordering rule"
        );
    }
}

/// **Question.** Does the overlap class only arise from the flush del+ins pair?
///
/// **No — a repeat typing reaches the same end.** `c.[72_*1del;*2_*3insTT]`
/// keeps its deletion and re-types the insertion as a four-unit `T` repeat
/// starting at `c.*1`: `c.[72_*1del;*1_*2T[4]]`. The deletion already claims
/// `c.*1`, so the repeat's tract overlaps its sibling and the allele again
/// denotes nothing.
///
/// **This is the typing stage widening a member past what the partition granted
/// it** — the same stage `fix/typing-must-not-widen-a-member` (#1571) addresses
/// for a different shape. Recorded here so the two are visibly one family: a
/// member's rendered extent must be bounded by the territory its partition
/// assigned, whichever edit type it renders as.
#[test]
fn a_repeat_typing_at_the_cds_end_overlaps_its_sibling_deletion() {
    let core = acgt_core();
    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        let output = normalize_3prime(&frame, "NM_TEST.1:c.[72_*1del;*2_*3insTT]");
        // The premise the doc comment states, asserted rather than described:
        // the emitted allele really does denote nothing. Pinning only the
        // spelling would leave "denotes nothing" as a claim no assertion checks,
        // and a fix that kept the string while repairing the overlap — or the
        // reverse — would go unnoticed in both directions.
        assert_eq!(
            denotation_of(frame.provider(), frame.served(), &output),
            Denotation::NoSequence,
            "{strand:?}: the repeat's tract must actually overlap its sibling, leaving the \
             allele denoting no sequence"
        );
        assert_eq!(
            output, "NM_TEST.1:c.[72_*1del;*1_*2T[4]]",
            "PINNED DEFECT — `72_*1del` already claims c.*1, so the `*1_*2T[4]` \
             tract overlaps it and the allele denotes no sequence ({strand:?})"
        );
    }
}

// ---------------------------------------------------------------------------
// The codon gate splits a spanning `delins` that its own members do not reach
// ---------------------------------------------------------------------------

/// **Question.** `general.md:35`'s exception has two conjuncts — *separated by
/// one nucleotide* **and** *together affecting one amino acid* — and
/// `coalesce_coding_frame_separation` shipped testing only the first. Restoring
/// the second is a conformance fix. What does it cost?
///
/// **Six of the corpus's 3' families stop converging, and it is always the
/// spanning-`delins` respelling that moves.** Promoted here because
/// `spec_conformance_axis`'s 3' `converged` figure went 9,140 -> **9,139** — the
/// one direction that census's own instruction forbids without a re-bless and a
/// named test. Six is the gross figure; five other families *gained*
/// convergence in the same change, which is where the net -1 comes from.
///
/// The six were three designs on each of the plus and minus coding multi-exon
/// shapes, all on the `AT` core (`s00`):
///
/// ```text
/// s00-c3{p,m}-m3-all-del-p1-sep3       s00-c3{p,m}-m4-all-del-p1-sep2
/// s00-c3{p,m}-pair-del-del-p1-sep8
/// ```
///
/// In every one the authored multi-member spelling is **unchanged** and the
/// spanning `delins` — which used to merge its way down to the members' own
/// answer — now stops at a finer partition, because at least one of the joins it
/// used to make spans two codons. So this is not a case of two answers competing
/// on the merits: the exception simply does not reach the pair, and
/// `general.md:34`'s plain rule governs it.
///
/// **Four of those six have since re-converged and are no longer pinned here.**
/// #1649 lets `merge`'s payload splitter express *deletion, retained reference,
/// deletion* — the mirror of the two-insertion shape it already expressed — and
/// with the finer partition available the spanning `delins` reaches its members'
/// answer again on `m3-all-del-p1-sep3` and `pair-del-del-p1-sep8`, on both
/// strands. That is a re-convergence rather than a competing answer: the two
/// spellings now denote one sequence *and* produce one string, and
/// `general.md:35` still does not reach either row — nothing was narrowed back to
/// a shape test to get there. This test's own `assert_ne!` prescribed the
/// remedy (lower `split_two`, raise `converged`, delete the row), and the
/// `spec_conformance_axis` re-bless is in the same commit; see that module's
/// third RE-BLESSED section for the row-id diff behind it.
///
/// **`s00-c3{p,m}-m4-all-del-p1-sep2` is untouched and is what remains below.**
/// Its spanning `delins` still stops where `general.md:34` puts it, so everything
/// this test was promoted to say still holds for it.
///
/// **The members' side moved once, in #1716, and it moved toward this test's own
/// clause.** It used to read `c.[24del;30_33delinsA]`; that `delins` spans
/// `c.30..c.33`, i.e. codon 10 (28-30) and codon 11 (31-33), so it was itself a
/// merge `general.md:35` cannot license — the per-member codon-frame predicate in
/// `merge::merge_consecutive_edits` was testing its left anchor's right edge
/// rather than the span it authorised. With the span tested, the pair stays
/// individual and the answer is `c.[24del;30_31del;33del]`. The two spellings
/// still disagree, so the row stays; only the fifth column below changed.
///
/// What remains unanswered is whether the *members'* answer is reachable from the
/// `delins` at all under the restored precondition. What is **not** unanswered is
/// the neighbouring record: `codon-carve-out-shape-restriction` is `decided`, and
/// it runs the same way — WIDEN, the exception applies wherever its precondition
/// holds, regardless of edit type, because edit type is a property of the
/// spelling. So the predicate may not be narrowed back to a shape test in order
/// to recover the rows it still costs.
///
/// **This is churn, not a rank-1 defect**, and that is asserted rather than
/// claimed: both outputs are checked through `denotation_of` to denote the row's
/// own bases. A fix that converges these must therefore choose between two legal
/// descriptions, which is `canonical-form-choice-when-both-legal` — `decided`,
/// and it says to derive from the resulting sequence rather than to preserve
/// either previously-shipped string.
///
/// Named rather than left in the corpus for the usual reason: a later generator
/// edit could stop emitting the `sep2` separation, or stop respelling a design as
/// a spanning `delins` at all, and the regression would vanish with the rows
/// (#1456/#1460/#1478).
///
/// # #1835 — THE FAMILY CONVERGED, AND THIS ROW NOW ASSERTS THAT
///
/// The spanning respelling reaches `c.[24del;30_31del;33del]`, which is what the
/// authored member spelling already reached — the two agree. The paragraph above
/// anticipated exactly this and named its licence: "A fix that converges these
/// must therefore choose between two legal descriptions, which is
/// `canonical-form-choice-when-both-legal` — `decided`, and it says to derive
/// from the resulting sequence rather than to preserve either previously-shipped
/// string." The default arm derives, so the spanning spelling is no longer
/// preserved and lands where the members already were.
///
/// **The test name is now historical.** It is kept because three sibling modules
/// cite it by name (`cis_confluence_axis` and `spec_conformance_axis`), and
/// renaming it would silently orphan those references; read the assertions.
///
/// **The old body's instruction is followed only in part, deliberately.** It said
/// "If they now agree the family has converged again — lower `split_two` and
/// raise `converged` in `spec_conformance_axis` and delete this row." The row is
/// NOT deleted: its two remaining assertions are the denotation guards, which are
/// what separate "converged" from "a member was dropped", and deleting them would
/// remove the only check that this row's convergence is not sequence loss. The
/// `spec_conformance_axis` figures are re-blessed in this same change.
///
/// What is asserted now: both spellings reach one string, that string denotes the
/// row's own bases, and the denotation is a real sequence rather than a
/// degenerate one.
#[test]
fn the_codon_gate_splits_a_spanning_delins_its_own_members_do_not() {
    let core = at_core();
    // `(row id, the spanning-delins respelling, its output, the authored member
    // spelling, the answer every member spelling reaches)`. Before #1599 the
    // third column equalled the fifth here, which is what made the family
    // converge.
    //
    // `m3-all-del-p1-sep3` and `pair-del-del-p1-sep8` used to sit alongside this
    // row and were removed by #1649, which re-converged them — see the doc above.
    // #1835: the third column is now equal to the fifth — the family converged,
    // which is the state the comment above says made it converge before #1599.
    let rows = [(
        "m4-all-del-p1-sep2",
        "NM_TEST.1:c.24_33delinsAATTTA",
        // Was `c.[24T>A;26_29del;32_33delinsTA]` until #1835.
        "NM_TEST.1:c.[24del;30_31del;33del]",
        "NM_TEST.1:c.[24del;27del;30del;33del]",
        // Was `c.[24del;30_33delinsA]` until #1716 — see the doc above.
        "NM_TEST.1:c.[24del;30_31del;33del]",
    )];

    for strand in [Strand::Plus, Strand::Minus] {
        let frame = Frame::build(RefShape::CodingMultiExon(strand), &core);
        for (design, spanning, spanning_output, members, members_output) in rows {
            // The half that did NOT move, asserted first so a future failure says
            // which side drifted.
            assert_eq!(
                normalize_3prime(&frame, members),
                members_output,
                "{design} ({strand:?}): the authored member spelling's answer is the one #1716 \
                 left it at, with every span the CODON-FRAME arm authorises inside one codon \
                 — `c.30_31del` is a merged span and straddles codons 10/11, but it is the \
                 strict-adjacency arm's, which `general.md:35` never gated — if this moved, \
                 the divergence below has a different cause than the one recorded here"
            );

            let output = normalize_3prime(&frame, spanning);
            assert_eq!(
                output, spanning_output,
                "{design} ({strand:?}): the spanning respelling is re-derived from the resulting \
                 sequence (`canonical-form-choice-when-both-legal`, decided) rather than \
                 preserved, so it lands on the partition `general.md:34` gives it"
            );
            // #1835: this was an `assert_ne!` pinning the divergence. The family
            // has converged, so the assertion is inverted — a re-divergence is
            // now what fails, and it would be a confluence regression rather than
            // a re-pin.
            assert_eq!(
                output, members_output,
                "{design} ({strand:?}): the two spellings of one variant must converge. They \
                 diverged from #1599 until #1835; if they diverge again, that is a confluence \
                 regression and `spec_conformance_axis`'s `converged`/`split_two` figures move \
                 with it"
            );

            // …and the agreement is about a real sequence. Without this the row
            // would be equally consistent with a member having been dropped,
            // which is a rank-1 defect and would have to be reported as one.
            let denoted = denotation_of(frame.provider(), frame.served(), &output);
            assert_eq!(
                denoted,
                denotation_of(frame.provider(), frame.served(), members_output),
                "{design} ({strand:?}): the two outputs must denote the SAME bases — that is \
                 what makes this a confluence failure rather than sequence loss"
            );
            assert!(
                matches!(denoted, Denotation::Sequence(_)),
                "{design} ({strand:?}): VACUOUS — both outputs must denote a real sequence for \
                 the equality above to mean anything, got {denoted:?}"
            );
        }
    }
}
