#!/usr/bin/env python3
"""Refresh tests/fixtures/mutalyzer-normalize/cases.json from upstream mutalyzer.

Pins the upstream commit at MUTALYZER_SHA. Run by hand when we choose to
sync with upstream:

    pixi run python scripts/refresh-mutalyzer-fixtures.py refresh

The script reads tests/variants_set.py from the pinned mutalyzer checkout
WITHOUT modifying that checkout's working tree (uses `git show <sha>:<path>`).
It then exec()s that file in an isolated namespace to extract TESTS_ALL and
serializes the cases to cases.json. Python tuples become JSON arrays; None
becomes null.

The script also exposes a one-shot `annotate-xfails` subcommand used during
initial import to record which axes are expected to fail for which inputs.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

# --- Pin to a specific upstream commit ---------------------------------------
MUTALYZER_SHA = "00045d63feba04ccff18a4d95f4245ad5d8d3092"  # "Bump version to 3.1.1"
MUTALYZER_REPO = Path.home() / "work" / "git" / "mutalyzer"
VARIANTS_SET_REL = "tests/variants_set.py"

# --- Output paths -------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "mutalyzer-normalize"
CASES_JSON = FIXTURE_DIR / "cases.json"
NOTICE = FIXTURE_DIR / "NOTICE"


def read_variants_set_at_sha() -> str:
    """Read variants_set.py from the pinned commit without mutating the
    upstream checkout. Returns the file's source as a string."""
    if not MUTALYZER_REPO.exists():
        sys.exit(f"error: mutalyzer repo not found at {MUTALYZER_REPO}")
    out = subprocess.check_output(
        ["git", "-C", str(MUTALYZER_REPO), "show", f"{MUTALYZER_SHA}:{VARIANTS_SET_REL}"],
        text=True,
    )
    return out


def load_tests_all() -> list[dict]:
    """Exec variants_set.py source in an isolated namespace and return TESTS_ALL."""
    source = read_variants_set_at_sha()
    ns: dict = {}
    exec(compile(source, f"{MUTALYZER_SHA}:{VARIANTS_SET_REL}", "exec"), ns)
    tests_all = ns.get("TESTS_ALL")
    if tests_all is None:
        sys.exit("error: TESTS_ALL not defined in variants_set.py at the pinned SHA")
    return list(tests_all)


def to_jsonable(obj):
    """Recursively convert Python tuples/sets to lists for JSON serialization."""
    if isinstance(obj, (list, tuple)):
        return [to_jsonable(x) for x in obj]
    if isinstance(obj, (set, frozenset)):
        # Preserve order via sorted str repr for determinism across runs.
        return sorted((to_jsonable(x) for x in obj), key=lambda x: json.dumps(x, sort_keys=True))
    if isinstance(obj, dict):
        return {k: to_jsonable(v) for k, v in obj.items()}
    return obj


def normalize_case(case: dict) -> dict:
    """Project an upstream case dict into the cases.json shape.

    - Converts tuples/sets-of-tuples (e.g. coding_protein_descriptions) into
      lists of lists.
    - Ensures every case has an 'xfail' key (empty list by default).
    """
    out = to_jsonable(case)
    out.setdefault("xfail", [])
    return out


def cmd_refresh() -> None:
    tests_all = load_tests_all()
    cases = [normalize_case(c) for c in tests_all]

    payload = {
        "description": "Mutalyzer normalizer test cases",
        "source": "https://github.com/mutalyzer/mutalyzer",
        "source_commit": MUTALYZER_SHA,
        "license": "MIT",
        "refreshed_at": date.today().isoformat(),
        "cases": cases,
    }

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    with CASES_JSON.open("w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=False)
        fh.write("\n")

    NOTICE.write_text(
        f"""Mutalyzer normalizer test fixtures
==================================

Source:  https://github.com/mutalyzer/mutalyzer
Commit:  {MUTALYZER_SHA}
License: MIT (Leiden University Medical Center)

cases.json is generated by scripts/refresh-mutalyzer-fixtures.py from
tests/variants_set.py in the upstream repo at the pinned commit above.
The script reads the file via `git show <sha>:<path>` and does not modify
the upstream checkout's working tree.

To refresh against a newer upstream commit:
    1. Update MUTALYZER_SHA in scripts/refresh-mutalyzer-fixtures.py
    2. pixi run python scripts/refresh-mutalyzer-fixtures.py refresh
    3. Re-run the mutalyzer-normalize tests; annotate any new xfails via:
         pixi run python scripts/refresh-mutalyzer-fixtures.py annotate-xfails \\
           --axis <axis> --from /tmp/ferro-xfail/<axis>.txt
    4. Commit cases.json + NOTICE in a single commit.

The upstream MIT license requires attribution; this file satisfies that
requirement. See the upstream LICENSE for the full text.
"""
    )

    n_to_test = sum(1 for c in cases if c.get("to_test"))
    print(
        f"wrote {len(cases)} cases ({n_to_test} to_test) " f"to {CASES_JSON.relative_to(REPO_ROOT)}"
    )


def cmd_annotate_xfails(axis: str, failing_inputs_path: Path) -> None:
    """One-shot: add `axis` to xfail[] for every case whose `input` is listed
    in failing_inputs_path (one input per line).

    When upstream contains multiple cases with the same `input` (it occasionally
    does — same variant, different expected `normalized`/`genomic` etc.), we
    only mark the case if its actual axis output diverges from the expected
    on inspection. The conservative thing is to mark every duplicate;
    over-marked cases will surface as XPASS on the next run and can be
    manually demoted.
    """
    failing = {
        line.strip() for line in failing_inputs_path.read_text().splitlines() if line.strip()
    }
    if not failing:
        print(f"no inputs to annotate (file {failing_inputs_path} was empty)")
        return
    data = json.loads(CASES_JSON.read_text())
    n_updated = 0
    for case in data["cases"]:
        if case.get("input") in failing:
            xfails = case.setdefault("xfail", [])
            if axis not in xfails:
                xfails.append(axis)
                n_updated += 1
    with CASES_JSON.open("w") as fh:
        json.dump(data, fh, indent=2, sort_keys=False)
        fh.write("\n")
    print(f"annotated {n_updated} cases with xfail={axis!r}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("refresh", help="regenerate cases.json from pinned upstream SHA")
    ann = sub.add_parser("annotate-xfails", help="record xfailed inputs for an axis")
    ann.add_argument("--axis", required=True)
    ann.add_argument("--from", dest="from_file", type=Path, required=True)
    args = parser.parse_args()
    if args.cmd == "refresh":
        cmd_refresh()
    elif args.cmd == "annotate-xfails":
        cmd_annotate_xfails(args.axis, args.from_file)


if __name__ == "__main__":
    main()
